Documentation update for vi.mock in the API section
vitest-dev/vitest pull request #1021
Opened 2022-03-24 16:02 UTC by calebwaldner

Adds more details and an example on how to use a factory function for mocked modules; specifically modules with a default export.

2022-03-24 16:13 UTC, sheremet-va requested changes

2022-03-24 16:13 UTC, sheremet-va commented on docs/api/index.md
> +      namedExport: ()=({})
```suggestion
      default: { myDefaultKey: vi.fn() }
      namedExport: vi.fn()
```

2022-03-24 16:22 UTC, dammy001 commented on docs/api/index.md
> +  - If mocking a module with a default export, you'll need to provide a `default` key within the returned factory function object. This is an ES modules specific caveat, therefor `jest` documentation
```suggestion
  - If mocking a module with a default export, you'll need to provide a `default` key within the returned factory function object. This is an ES modules specific caveat, therefore `jest` documentation may differ as `jest` uses commonJS modules. *Example:*
```

2022-03-25 04:38 UTC, sheremet-va approved these changes

2022-03-25 07:03 UTC, merged