fix: cache path of modules imported in setup file
vitest-dev/vitest pull request #1545
Opened 2022-06-25 09:46 UTC by konpeki622

2022-06-25 09:49 UTC, sheremet-va commented
This doesn't seem right. `vi.mock` doesn't work because we already imported a file and it exists inside a cache. We need to remove it, if we are mocking it, that's all.

2022-06-25 10:01 UTC, konpeki622 commented
> This doesn't seem right. `vi.mock` doesn't work because we already imported a file and it exists inside a cache. We need to remove it, if we are mocking it, that's all.

I mean that once a module was imported before mocking, its path should be cached. But now it cached two different paths from setup files and test files, though these two paths refered to one module, that means it will mock 'another' module. I made them to be the same absolute path.

2022-06-25 10:06 UTC, sheremet-va commented
> I mean that once a module was imported before mocking, its path should be cached. But now it cached two different paths from setup files and test files, though these two paths refered to one module, that means it will mock 'another' module. I made them be the same absolute path.

You are incorrect.

Their imported paths are the same. `vi.mock` mocks the correct module. It is not mocked in test, because in `request` it imports the cached one (`vite-node` doesn't know about mocks). This is why we should removed actual module from cache - it is no longer needed.

2022-06-25 10:07 UTC, sheremet-va requested changes

2022-06-25 10:07 UTC, sheremet-va commented on test/core/test/imports.test.ts
> +  expect(stringTimeoutMod).toStrictEqual(variableTimeoutMod)
No, it should `BE` the same module - have the same reference

2022-06-25 10:07 UTC, sheremet-va commented on packages/vitest/src/runtime/setup.ts
> +        await import(file)
We shouldn't silently skip this

2022-06-25 10:22 UTC, konpeki622 commented
Well, I will leave this question open and find why that makes test fail. 🤔

2022-06-27 06:38 UTC, sheremet-va requested changes
As I said, this is wrong solution. To fix the problem you are linking to, we need to load mocked version first. They have the same path. It has nothing to do with this function.

The mocked version is not loaded, because module is already cached:

https://github.com/vitest-dev/vitest/blob/b054cd5e3664055aed47a5818c7f2b79fb90ed97/packages/vite-node/src/client.ts#L85

All caches a have a key similar to `${path}__mock`.

2022-06-27 06:38 UTC, sheremet-va commented on packages/vite-node/src/utils.ts
> +export function toFilePath(id: string, root: string, raw = false): string {
This became very confusing. Why as a developer I should use `raw` here? This function should just work, I already gave it path

2022-06-27 07:02 UTC, closed without merging