Edge runtime
vitest-dev/vitest pull request #1574
Opened 2022-06-30 08:49 UTC by promer94

add environment support for https://github.com/vercel/edge-runtime

## limitations
`eval` and `new Function()` still works in vitest edge environment. 
#1470 might help to solve this problem
```js
// ❌ Fail
// Error name:    "EvalError"
// Error message: "Code generation from strings disallowed for this context"
it('should return the correct value', () => {
  let val = eval('2 + 2');
  expect(val).toBe(4);
});

```

2022-06-30 13:25 UTC, antfu approved these changes
I like this in general. Just a few details need to discuss

2022-06-30 13:25 UTC, antfu commented on docs/config/index.md
> +- **Type:** `'node' | 'jsdom' | 'happy-dom' | 'edge'`
```suggestion
- **Type:** `'node' | 'jsdom' | 'happy-dom' | 'edge-runtime'`
```

`edge` feels too general without knowing the context, maybe better to be `edge-runtime`?

2022-06-30 13:57 UTC, antfu commented on packages/vitest/src/integrations/env/index.ts
> +export const envNpm = {
```suggestion
export const envPackageNames: Record<keyof typeof environments, string> = {
```

2022-06-30 13:57 UTC, antfu commented on packages/vitest/src/node/cli-api.ts
> +    const packName = envNpm[ctx.config.environment]
```suggestion
    const packageName = envNpm[ctx.config.environment]
```

2022-07-01 09:00 UTC, antfu approved these changes

2022-07-01 11:30 UTC, sheremet-va requested changes
Should we also add `@edge-runtime/vm` to peerDependencies? We have all other envs there

2022-07-02 09:28 UTC, sheremet-va approved these changes

2022-07-02 09:51 UTC, merged