feat: check related against forceRerunTriggers
vitest-dev/vitest pull request #1595
Opened 2022-07-04 10:25 UTC by elliotwestlake

**IF** forceRerunTriggers has values in it
**THEN** use `micromatch` to see if there's a file in `related` that should trigger the whole test suite

2022-07-04 10:27 UTC, sheremet-va requested changes
LGTM except for lock file

2022-07-04 10:31 UTC, elliotwestlake commented on pnpm-lock.yaml
> +    resolution: {integrity: sha512-0ckx7ZHRPqb0oUm8zNr+90mtf9DQB60H1wMCjBtfi62Kl3a7JbHob6gA2bC+xRvZoOL+1hzUK8jeuEIQE8svEQ==}
Not sure why this changed, should be sorted now

2022-07-04 10:31 UTC, sheremet-va commented
> Was going to write some tests for this, but not sure where they should go

I don't think we have unit tests for those, but we have `test/related`. You can add integration test there. You will need to call tests with custom config `vitest related some-file.js -c custom-config-with-force-rerun.js`:

```
// package.json
{
  "scripts": {
    "test": "nr test:related && nr test:rerun",
    "test:related": "<current test command>",
    "test:rerun": "<your test command>"
  }
}
```

2022-07-04 10:37 UTC, sheremet-va commented
Also, please, add more information to the docs of `--changed` and `--forceRerunTriggers`.

2022-07-04 14:12 UTC, elliotwestlake commented on pnpm-lock.yaml
> +    resolution: {integrity: sha1-yayFsqX9GENbjIXZ7LUObWyJP/g=}
not sure why this keeps changing

2022-07-04 14:48 UTC, sheremet-va requested changes

2022-07-04 14:48 UTC, sheremet-va commented on pnpm-lock.yaml
> +    resolution: {integrity: sha1-yayFsqX9GENbjIXZ7LUObWyJP/g=}
Just don't push it

2022-07-05 04:39 UTC, sheremet-va approved these changes
LGTM

2022-07-05 04:48 UTC, antfu approved these changes

2022-07-05 05:58 UTC, sheremet-va commented
@elliotwestlake should we add new defaults to `forceRerunTriggers`? 🤔 Like `package.json`, maybe `vitest.config.*`, `vite.config.*` 🤔

2022-07-05 07:12 UTC, elliotwestlake commented
> @elliotwestlake should we add new defaults to `forceRerunTriggers`? 🤔 Like `package.json`, maybe `vitest.config.*`, `vite.config.*` 🤔 (maybe `dist`? anything else?)
> 
> 
> 
> If yes, this should also be specified in docs.

Great idea, will add them and any others I can think of!

2022-07-05 07:56 UTC, elliotwestlake commented
@sheremet-va Any chance you could enable auto-merge again please? The checks weren't running with your commit for some reasone

2022-07-05 08:04 UTC, merged