feat: add option for ignoring unhandled errors
vitest-dev/vitest pull request #1678
Opened 2022-07-19 10:41 UTC by DerYeger

I recently migrated a large project from Jest to Vitest.
During the migration, I encountered issues with unhandled errors due to race condition (caused by poor tests that didn't clean up their async React hooks).
Since there's a huge number of tests without any way of finding the few rare occasions of such issues, I had to use `patch-package` to prevent Vitest from failing due to unhandled errors.

I am aware that this isn't the proper way, but there was no other way of getting around this issue.|

With this PR, I propose a new config options for ignoring unhandled errors.
It's fittingly labelled `dangerouslyIgnoreUnhandledErrors`.

2022-07-19 14:41 UTC, sheremet-va requested changes
I would much prefer if we could provide a better way of displaying errors to help users find the issues, instead of ignoring it.

2022-07-19 14:50 UTC, DerYeger commented
> I would much prefer if we could provide a better way of displaying errors to help users find the issues, instead of ignoring it.

While I agree, I'm not sure if much can be done about improving the reports of unhandled errors.
I'd be happy to work on a solution if someone has an idea.

With the proposed option enabled, Vitest's behaviour would match the behaviour of older Jest versions, making iterative migration much simpler.

2022-07-19 19:46 UTC, antfu commented
Or maybe we return a different exitCode so you could ignore it with a UNIX pipe or some ci config?

2022-07-19 20:14 UTC, DerYeger commented
> Or maybe we could return a different exitCode so you could ignore it with a UNIX pipe or some ci config?

I guess that would work as well (if actually failing tests in presence of unhandled errors still result in exit code 1).

Though it would also have downsides compared to the config option (no central config, no platform independence, can't call package script differently like `nr test --no-ui`).

2022-07-22 07:29 UTC, antfu commented
I am fine with adding the option, since we have the `--dangerously` prefix

2022-07-26 03:31 UTC, antfu approved these changes

2022-07-26 05:29 UTC, sheremet-va approved these changes

2022-07-26 05:58 UTC, merged