fix: normalize `moduleCache` path
vitest-dev/vitest pull request #1740
Opened 2022-07-29 10:39 UTC by ChpShy

fix: #1714

This problem is caused by the `moduleCache` key is not same in setup file and the vue component.
In setup file, the key is `/@fs/user/../node_modules/vue-meta/dist/vue-meta.cjs.js`, but in the component, is `/node_modules/vue-meta/dist/vue-meta.cjs.js`.

I'm not sure if this solution is the best, if not, modifications or rewrites are welcome~

2022-07-29 13:14 UTC, sheremet-va requested changes
Can you add a test for this?

2022-07-29 14:47 UTC, ChpShy commented
> Can you add a test for this?

ok. I will do it later.

2022-07-29 15:13 UTC, jagoncalves14 commented
Thanks for this @ChpShy.
I applied your change directly in my node_modules/vitest folder to see if it fixes it — and it did! 👏

2022-07-30 00:29 UTC, ChpShy commented
I'm confused that I can't reproduce this in `vitest` test. Maybe someone more familiar with `vite` and `vitest` could help with add test? Or I need more time to reproduce it.

2022-07-31 00:49 UTC, ChpShy commented
It looks like it is caused by `pnpm workspace`,  In workspace package, test success, because `vue component` also compiled to be `/@fs/Users/xxx/node_modules/.pnpm/vue-meta@3.0.0-alpha.10_vue@3.2.37/node_modules/vue-meta/dist/vue-meta.cjs.js`.

But in demo project, test failed, because `vue component` compiled to be `/node_modules/.pnpm/vue-meta@3.0.0-alpha.10_vue@3.2.37/node_modules/vue-meta/dist/vue-meta.cjs.js`.

And `callFunctionMock` is private, So, how can I add the test? @sheremet-va

2022-07-31 00:53 UTC, ChpShy commented
Also, this maybe caused by vite. I'm not sure. Maybe someone can help to provide a reason? Hope for feedback~

2022-07-31 00:54 UTC, ChpShy commented
> because

I also test the different version of `vite`. It get the same result.

2022-07-31 05:35 UTC, sheremet-va commented
> So, how can I add the test?

You can add a unit test:

```ts
const mockMap = {
  ...your mocks
}
const mocker = new Mocker({ ...options })
const result = mocker.request(pathThatFailedBefore)
```

2022-07-31 06:20 UTC, ChpShy commented
I think this had been resolved by pr  #1726

line: https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/runtime/mocker.ts#L298

Waiting for release~

2022-07-31 06:20 UTC, closed without merging