fix: filter out Symbol.hasInstance
vitest-dev/vitest pull request #1757
Opened 2022-07-31 13:17 UTC by nieyuyao

fix #1671

2022-08-02 01:09 UTC, QGerrit approved these changes

2022-08-02 01:27 UTC, QGerrit reviewed
This unfortunately doesn't seem to quite be enough to fix #1671.... at least fully. After manually applying this patch locally, my tests started failing with `TypeError: Cannot read properties of undefined (reading 'dataEmitted')`. `jsdom` test environment in a very basic vue3 app.... oddly, `dataEmitted` doesn't seem to appear anywhere in my node_modules tree.

2022-08-02 03:18 UTC, nieyuyao commented
> This unfortunately doesn't seem to quite be enough to fix #1671.... at least fully. After manually applying this patch locally, my tests started failing with `TypeError: Cannot read properties of undefined (reading 'dataEmitted')`. `jsdom` test environment in a very basic vue3 app.... oddly, `dataEmitted` doesn't seem to appear anywhere in my node_modules tree.

emmm.... I tried to find the reason and converted the PR into draft

2022-08-02 03:34 UTC, nieyuyao commented
This `TypeError: Cannot read properties of undefined (reading 'dataEmitted')` comes from [here](https://github.com/nodejs/node/blob/948712bc4c4b24edc238222ba6a7e585f51d01ef/lib/internal/streams/readable.js#L1172). Try to read the readableDidRead property and assign to the container when mocking. However, the Readable has not been initialized yet, so an error is thrown.

2022-08-02 14:21 UTC, QGerrit commented
Wow, good find! I forgot to mention I was doing `vi.mock('axios')`, that break location makes more sense now.

2022-08-04 03:53 UTC, simon-abbott requested changes
I don't like this solution. There are valid cases where we _do_ want to mock `Symbol.hasInstance`, and, as you've noticed, this doesn't actually fix the root cause.

I'm working on a fix for the underlying issue which should be up shortly.

2022-08-04 03:53 UTC, simon-abbott commented on packages/vitest/src/runtime/mocker.ts
> +      && ['arguments', 'callee', 'caller', 'length', 'name', Symbol.hasInstance].includes(prop)
I don't like this solution. There are valid cases where we _do_ want to mock `Symbol.hasInstance`, and, as you've noticed, this doesn't actually fix the root cause.

2022-08-04 15:35 UTC, simon-abbott commented
I've solved #1671 in a more general way over in #1786.

2022-08-06 03:38 UTC, closed without merging