fix: importActual path resolution for non-child paths (fix #1864)
vitest-dev/vitest pull request #1868
Opened 2022-08-17 18:06 UTC by simon-abbott

This fixes two similar bugs with `importActual`'s path resolution:

1. #1864, importing from sibling directories would try to import from sub directories instead.
2. Importing from a sibling directory that starts with the root path would snip the root off the path (for example, `path = '/foo/bar-baz'` with `root = '/foo/bar'` results in an output of `-baz`)

Fixes #1864.

2022-08-17 19:48 UTC, simon-abbott commented
Ok I have no idea why that one CI run failed. If anyone knows please let me know so I can fix it!

2022-08-22 15:38 UTC, simon-abbott commented
@antfu Could this be merged soon? This is completely blocking my ability to convert our application over to vitest.

2022-08-22 15:42 UTC, sheremet-va requested changes

2022-08-22 15:56 UTC, simon-abbott commented on packages/vite-node/src/utils.ts
> +      if (existsSync(resolved.replace(/\?.*$/, '')))
Yeah. The issue is that it is currently used in non-async locations (specifically the constructor in the `defineWebWorker` constructor). I can make this async, but that would require refactoring that constructor, probably into a static `create` helper. If you're ok with that change I'll refactor it.

2022-08-23 04:26 UTC, sheremet-va commented on packages/vite-node/src/utils.ts
> +      if (existsSync(resolved.replace(/\?.*$/, '')))
Async will be even slower tbh.

2022-08-23 16:04 UTC, simon-abbott commented on packages/vite-node/src/utils.ts
> +      if (existsSync(resolved.replace(/\?.*$/, '')))
If we don't do the existence check then either we need to treat all absolute paths as actually being absolute (which will fix #1864 but will break other stuff), or we treat all absolute paths as relative to the root (which means #1864 remains broken). I would strongly prefer to do the former, treating absolute paths as actually being absolute, but that re-rooting process was clearly put in to fix some issue and I don't want to have a regression. This was the only way I could find to fix the issue without breaking whatever it was that necessitated the re-rooting in the first place.

2022-08-31 15:23 UTC, sheremet-va requested changes

2022-08-31 15:48 UTC, simon-abbott commented on packages/vite-node/src/utils.ts
> +      if (existsSync(resolved.replace(/\?.*$/, '')))
Ok, seems I have to go back to the drawing board then, and likely fix whatever has been passing absolute paths that aren't actually absolute paths. That's gonna be a pain. Do you happen to know what necessitated this code in the first place, so I have a starting point?

2022-08-31 15:53 UTC, sheremet-va commented on packages/vite-node/src/utils.ts
> +      if (existsSync(resolved.replace(/\?.*$/, '')))
Unfortunately I don't know, but I assume we have test for it to not cause regression.

2022-08-31 15:57 UTC, sheremet-va commented on packages/vite-node/src/utils.ts
> +      if (existsSync(resolved.replace(/\?.*$/, '')))
I personally don't think it's `toFilePath` fault, I would look into `importActual`, since actual imports are working fine.

2022-10-28 08:03 UTC, sheremet-va commented
@simon-abbott We might try this approach anyway. Do you think you can resolve conflicts?

2022-10-31 09:36 UTC, merged