docs: add information about benchmarking
vitest-dev/vitest pull request #2001
Opened 2022-09-08 08:44 UTC by sheremet-va

I've added minimum information that I could gather. @antfu @poyoho, please, if you have anything to add, feel free to push to this PR

2022-09-08 12:47 UTC, nickmccurdy requested changes
Looks good so far. It could be nice to have some info on what the CLI output means too, especially for users not familiar with benchmarking or statistics.

2022-09-08 13:07 UTC, poyoho approved these changes
nice!

2022-09-08 14:58 UTC, Aslemammad commented
Is it possible to include `tinybench` in the main doc file, like what is with tinyspy and tinybench? Thanks.

2022-09-10 07:54 UTC, antfu approved these changes

2022-09-10 07:54 UTC, merged