fix(vitest) align .each behavior with jest
vitest-dev/vitest pull request #2064
Opened 2022-09-20 18:52 UTC by bartoszgolebiowski

close #1858

2022-09-22 05:25 UTC, sheremet-va requested changes

2022-09-22 05:25 UTC, sheremet-va commented on test/core/test/each.test.ts
> +])('if all cases are arrays of equal length, treats array elements as arguments', (value) => {
Shouldn't we check both `(value1, value2)`?

2022-09-22 05:25 UTC, sheremet-va commented on test/core/test/each.test.ts
> +  describe.each([null, [null]])('null is null', (value) => {
maybe there are better names for these tests? there are 3 tests named `null is null`, but they check `[null] === [null]` 🤔

2022-11-07 10:42 UTC, antfu approved these changes

2022-11-07 12:04 UTC, merged