feat: support string template
vitest-dev/vitest pull request #2337
Opened 2022-11-16 02:50 UTC by poyoho

fix: #2335

2022-11-16 07:33 UTC, sheremet-va requested changes
Thank you for the PR, but it needs more work:

1. Vitest also has `describe.each`, and it should support the same API
2. We need documentation for this feature

2022-11-16 07:44 UTC, poyoho commented
ok. wait me later

2022-11-21 14:09 UTC, sheremet-va requested changes

2022-11-21 14:09 UTC, sheremet-va commented on docs/api/index.md
> +    a    | b    | expected
Let's make it more readable, can you add more spaces, so `|` character visually forms a table?

2022-11-21 14:09 UTC, sheremet-va commented on docs/api/index.md
> +    ${'a'} | ${'b'} | ${'ab'}
The same here

2022-11-22 07:16 UTC, sheremet-va approved these changes

2022-11-22 07:16 UTC, merged