fix(cli): allow overrides reporter via cli option
vitest-dev/vitest pull request #2573
Opened 2022-12-28 14:44 UTC by mysteryven

fix: #2537

2022-12-28 15:54 UTC, sheremet-va requested changes

2022-12-28 15:54 UTC, sheremet-va commented on packages/vitest/src/node/config.ts
> +    const reporter = resolved.reporter
```suggestion
    const reporters = resolved.reporter ?? resolved.reporters
    resolved.reporters = Array.from(new Set(
      toArray(resolved.reporters)),
    ).filter(Boolean)
```

2022-12-30 03:03 UTC, mysteryven commented
The CI is always down on ubuntu, I am trying to solve it, please wait some time :)

2022-12-31 13:18 UTC, sheremet-va approved these changes

2023-01-01 14:37 UTC, merged