fix: Removed setup files from coverage by adding them on coverage.exclude
vitest-dev/vitest pull request #2574
Opened 2022-12-29 05:50 UTC by g4rry420

Signed-off-by: GurkiranSingh <gurkiransinghk@gmail.com>

Ref: https://github.com/vitest-dev/vitest/pull/2489
Closes: #2190

2022-12-31 11:39 UTC, sheremet-va requested changes
Please, add an actual test case to `test/coverage`. Current test is pretty meaningless.

2022-12-31 11:39 UTC, sheremet-va commented on packages/vitest/src/node/config.ts
> +  resolved.coverage.exclude.push(...resolved.setupFiles.map(file => file.replace(`${resolved.root}/`, '')))
Maybe it's better to use `relative` from `pathe` module?

2022-12-31 21:40 UTC, g4rry420 commented
Thank you for suggesting the use of `relative` from `pathe` module. I have added that.
For testing, honestly, I am not really good with it. Can you please suggest me what should I add in it ?

2023-01-01 14:37 UTC, sheremet-va commented
> Thank you for suggesting the use of `relative` from `pathe` module. I have added that.
> For testing, honestly, I am not really good with it. Can you please suggest me what should I add in it ?

There is `test/coverage-test` folder. You need to add a setup file and check that it's not in the report.

2023-01-06 20:44 UTC, sheremet-va requested changes
I don't see a check inside coverage test that setup file is not in a report?

2023-01-07 21:54 UTC, g4rry420 commented
I have added the test. Please, let me know if you see any issues :)

2023-01-07 21:57 UTC, g4rry420 commented
One thing, I have noticed is that, if for some reason, a user intentionally wants to include the `setup` file in the coverage, then they can't do that (even if they mention that file in the `coverage.include` option). I believe, this is expected.

2023-01-09 20:57 UTC, sheremet-va approved these changes

2023-01-10 04:26 UTC, AriPerkkio requested changes
Currently the test case does not fail if the implementation is commented out. Let's add some more checks there:

- Keep the current `setup.ts` and its test assertions as is
- Create `test/coverage-test/src/another-setup.ts`
- Use `src/another-setup.ts` as second setupFile in configuration
- Add assertions to the test case to check that it does not end up in the coverage report folder

Final test case should assert that both setupFiles are not present in coverage report.

2023-01-11 06:45 UTC, AriPerkkio approved these changes

2023-01-18 13:33 UTC, sheremet-va approved these changes
@AriPerkkio should we add a test that file imported in setupFile is still inside coverage report? This is expected behaviour, right?

```ts
// ./utils.ts
export function defineGlobal() {
  globalThis.testing = true
}
```

```ts
// ./vitest.setup.ts
import { defineGlobal } from './utils.ts'
defineGlobal()
```

Setup file should not be in the report, but utils should?

2023-01-18 13:34 UTC, sheremet-va requested changes
^ See comment above

2023-01-18 15:03 UTC, AriPerkkio commented
> This is expected behaviour, right?

The imported files will end up in coverage report and we should not try to change that - it would be quite complex. I don't think adding test case for validating it is that important.

The current changes look good to me, and tests are covering the functionality well.

2023-01-19 09:56 UTC, sheremet-va approved these changes

2023-01-19 09:57 UTC, merged