test: ui e2e
vitest-dev/vitest pull request #2710
Opened 2023-01-18 16:58 UTC by poyoho

feat e2e test for ui

ref: 2695

2023-01-19 08:45 UTC, sheremet-va commented
Doesn't seem like it's working:

<img width="625" alt="Screenshot 2023-01-19 at 09 45 32" src="https://user-images.githubusercontent.com/16173870/213395697-c12cb264-9704-40bc-8377-09e5879e6a0e.png">

2023-01-30 06:35 UTC, poyoho commented
@sheremet-va it's working now.

2023-02-03 09:34 UTC, sheremet-va requested changes

2023-02-03 09:34 UTC, sheremet-va commented on test/ui/test/html-report.spec.ts
> +  expect((await (await page.$('#app'))?.innerHTML() || '').length).not.toBe(0)
can we add a more elaborate check here? maybe `toMatch` and check for some HTML there

2023-02-11 20:16 UTC, merged