feat: Hide skipped test lines
vitest-dev/vitest pull request #2745
Opened 2023-01-25 01:14 UTC by g4rry420

Signed-off-by: GurkiranSingh <gurkiransinghk@gmail.com>

Resolves: #2647
- I have used `silentSkip` config option for user to hide the skipped tests. Please, feel free suggest any other name for this config.
- For testing, cd `examples/basic` and run `pnpm test`

2023-02-03 09:40 UTC, sheremet-va requested changes

2023-02-03 09:40 UTC, sheremet-va commented on examples/basic/test/basic.test.ts
> +test.skip('JSON', () => {
Please, don't modify tests in basic examples. They are used in https://vitest.new

2023-02-03 09:40 UTC, sheremet-va commented on examples/basic/vite.config.ts
> +    silentSkip: true,
What about `hideSkippedTests`? I think this should also be available as a CLI flag

2023-03-07 17:40 UTC, sheremet-va approved these changes

2023-05-02 22:14 UTC, thisRaptori commented
Hey! Any idea whether this will be merged? I, uh, have the same issue 😅 

<img width="528" alt="image" src="https://user-images.githubusercontent.com/19466326/235797287-a6d09989-1471-4536-9283-81f685536d88.png">

2023-05-03 09:20 UTC, merged