fix: removing obsolete warning log for snapshots
vitest-dev/vitest pull request #2782
Opened 2023-01-31 18:20 UTC by samkevin1

This removes the `obsolete` log for snapshots that are unchecked.

Related to #2442.

2023-01-31 18:44 UTC, sheremet-va requested changes
Vitest should still display obsolete snapshots, it should not display skipped ones as obsolete.

2023-01-31 18:52 UTC, samkevin1 commented
Got it, will change

2023-02-11 14:24 UTC, sheremet-va commented
> Vitest should still display obsolete snapshots, it should not display skipped ones as obsolete.

I think I might've phrased this in a wrong way. We don't want Vitest to notify users about skipped snapshots because this information is irrelevant. If we skipped a test, we don't want to remove these snapshots and don't want to show them alongside REALLY obsolete ones. But if we detected actually obsolete snapshots, we want to display them.

So, there are a few cases:

1. Vitest run a test, and all snapshots exist
   - Don't show any warnings
 2. Vitest skipped a test
    - Ignore snapshots inside, do not give a warning that there are obsolete snapshots for this test
 3. Vitest run a test, and found obsolete snapshots
    - Show a warning about obsolete snapshots

2023-02-16 18:16 UTC, samkevin1 commented
@sheremet-va can you rerun the failing test? Locally it doesn't break

2023-03-07 17:35 UTC, sheremet-va requested changes

2023-03-07 17:35 UTC, sheremet-va commented on packages/vitest/src/integrations/snapshot/manager.ts
> +  summary.skipped += result.skipped
We don't care for skipped snapshots. We already show that a test was skipped, it should be enough. 

We shouldn't show a user anything about skipped tests.

2023-03-07 17:35 UTC, sheremet-va commented on packages/vitest/src/integrations/snapshot/client.ts
> +    suite ? this.suite = suite : this.test = test
Why do we need a suite here? Snapshots are test specific, they should not rely on a suite.

2023-03-07 17:35 UTC, sheremet-va commented on packages/vitest/src/integrations/snapshot/port/state.ts
> +      if (keyToTestName(uncheckedKey).includes(testName)) {
I feel like the safer way would be to use a regular expression here.

2023-03-07 17:35 UTC, sheremet-va commented on packages/vitest/src/runtime/runners/test.ts
> +  async onBeforeRunSuite(suite: Suite) {
What is happening here?

2023-03-07 17:35 UTC, sheremet-va commented on packages/vitest/src/runtime/runners/test.ts
> +      this.snapshotClient.skipSuiteSnapshots(suite)
We should be able to mark skipped snapshots inside a test itself. 

```ts
getTasks(suite).forEach((test) => client.skipTestSnapshots(test))
```

2023-03-07 17:35 UTC, sheremet-va commented on packages/vitest/src/integrations/snapshot/client.ts
>      this.snapshotState?.markSnapshotsAsCheckedForTest(test.name)
Just use this to mark all tests, don't reinvent the wheel

2023-07-25 03:31 UTC, closed without merging