fix: duplicate callbacks in vite-node HMR
vitest-dev/vitest pull request #2792
Opened 2023-02-02 08:38 UTC by jgoux

When using vite-node HMR, the callbacks registered with:

```ts
if (import.meta.hot) {
  import.meta.hot.on("vite:beforeFullReload", () => {
    console.log("full reload");
    server.close();
  });
}
```

are duplicated/accumulated on each reload (logs below after 4 saves):

```bash
> vite-node --watch src/index.ts

listening on port 4000
full reload
listening on port 4000
full reload
full reload
listening on port 4000
full reload
full reload
full reload
listening on port 4000
full reload
full reload
full reload
full reload
listening on port 4000
```

This change ensures that if for the same event, two callbacks are identical, the old one is replaced with the new one.

We can't use reference identity check unfortunately as the identity of the callback change between reloads, hence the usage of `.toString()`.

2023-02-02 08:45 UTC, sheremet-va requested changes
Maybe it's better to remove callbacks when a module is invalidated? This doesn't seem very stable.

2023-02-02 08:48 UTC, jgoux commented
> Maybe it's better to remove callbacks when a module is invalidated? This doesn't seem very stable.

Sure, whatever works best. I don't have much knowledge about the internals of vite/vite-node. How should I do that?

2023-02-02 08:54 UTC, sheremet-va commented
>  I don't have much knowledge about the internals of vite/vite-node. 

So do I. I assume it should be possible to detect what module added a listener and remove it if it was invalidated.

2023-02-02 08:56 UTC, sheremet-va commented
> So do I. I assume it should be possible to detect what module added a listener and remove it if it was invalidated.

I think we can also just safely clear all "vite:onBeforeReload" listeners, because it assumes that everything will be reloaded

2023-02-03 09:19 UTC, sheremet-va approved these changes

2023-02-03 09:20 UTC, merged