feat(spy): Implement mock.withImplementation API
vitest-dev/vitest pull request #2835
Opened 2023-02-08 10:18 UTC by obadakhalili

Closes #2812.

This is my first contribution, so I might have missed a few test cases, or missed a better way to implement this. Hopefully, it won't be my last 😄.

**Note**: I don't think that this is the best implementation for the asynchronous version. It would be better if it was explicit that the stub method `.withImplementation` returns a promise when the passed callback is asynchronous, so the user knows that they have to use `async` with it.

I'm happy to make any further changes and change the docs as necessary.

2023-02-08 10:28 UTC, sheremet-va requested changes

2023-02-08 10:28 UTC, sheremet-va commented on packages/spy/src/index.ts
> +    else {
You don't call cb

2023-02-08 10:28 UTC, sheremet-va commented on packages/spy/src/index.ts
> +    if (cb.constructor.name === 'AsyncFunction') {
You can just check if cb returned a Promise

2023-02-08 10:28 UTC, sheremet-va commented on packages/spy/src/index.ts
> +  withImplementation(fn: ((...args: TArgs) => TReturns), cb: () => void): this
You can add overload for Promise cb

2023-02-08 10:28 UTC, sheremet-va commented on test/core/test/mocked.test.ts
> +      expect(mock()).toBe(2)
if you have expect inside a callback, don't forget to call
`expect.assertions` beforehand

2023-02-08 10:28 UTC, sheremet-va commented on test/core/test/mocked.test.ts
> +describe('temporary mock implementation', () => {
There are not enough tests. What if I used `mockImplementationOnce` before this function, for example? Or any other method for that matter

2023-02-10 11:16 UTC, mysteryven commented
I think the `withImplementation` should take precedence over `implementationOnce`. I created an [issue](https://github.com/facebook/jest/issues/13887) to Jest, and they fixed it now, maybe we can also add it.

2023-02-11 06:29 UTC, obadakhalili commented on test/core/test/mocked.test.ts
> +    /* NOTE:
The below caveat is annoying.

2023-02-11 12:56 UTC, sheremet-va commented
I changes types a bit, can you add documentation about this function with examples?

2023-02-12 13:43 UTC, obadakhalili commented
I added the docs. I have a few questions though:
1. This now renders `mockImplementationOnce` unnecessary, right?
2. Should we add a test case with `mock.restore/reset`? Maybe here it is enough to test that `getMockImplementation` returns the correct function reference when `withImplementation` is used, and to test those methods (`restore` & `reset`) independently. Or maybe a test with these methods isn't necessary here. What do you think?
3. One way to handle precedence over the `mockImplementationOnce` function is to clear the once implementations temporarily inside the function as opposed to using an extra variable `implementationChangedTemporarily`. Do you think we should do that?
4. The change you did prevents TS users to mock the implementation with a different return value type. What if they need to do this temporarily?
5. Finally, the change you did actually handled the TS caveat and made the `withImplementation` return a promise if the callback is asynchronous. Do you think you can tell me why your solution works but not mine?

A small note regarding your changes, I appreciate your help, though I would also like it to do it by myself so I get to benefit as much as possible. Thanks though 😄

2023-02-12 14:12 UTC, sheremet-va commented
> 1. This now renders `mockImplementationOnce` unnecessary, right?

How so? You can always chain them to return the value several times.

> 2. Should we add a test case with `mock.restore/reset`? Maybe here it is enough to test that `getMockImplementation` returns the correct function reference when `withImplementation` is used, and to test those methods (`restore` & `reset`) independently. Or maybe a test with these methods isn't necessary here. What do you think?

Sure, the more tests we have the better.

> 3. One way to handle precedence over the `mockImplementationOnce` function is to clear the once implementations temporarily inside the function as opposed to using an extra variable `implementationChangedTemporarily`. Do you think we should do that?

No, I think it's unnecessarily complex because we will need to restore them afterward.

> 4. The change you did prevents TS users to mock the implementation with a different return value type. What if they need to do this temporarily?

If a function defined its return type, it should always return that type. It doesn't make sense to return anything else there.

> 5. Finally, the change you did actually handled the TS caveat and made the `withImplementation` return a promise if the callback is asynchronous. Do you think you can tell me why your solution works but not mine?

Your order was wrong. `void` is subset of `Promise<void>`, so typescript always resolved it as `void`. If you change the order and define Promise overload first, it will work.

2023-02-13 19:31 UTC, obadakhalili commented
> How so? You can always chain them to return the value several times.

Yeah yeah, but I meant that `withImplementation` can do `mockImplementationOnce` work and more. So maybe `mockImplementationOnce` won't be as useful to users as before. Not suggesting to remove it. Just thought I would point it out.

2023-02-17 05:11 UTC, obadakhalili commented
Hey @sheremet-va, everything's fine with the PR? are you guys planning to merge it soon?

2023-02-24 08:24 UTC, obadakhalili commented
@sheremet-va I re-resolved the conflicts with the pnpm lock file. Is there a reason why you guys are taking long to merge the PR?

2023-02-24 19:23 UTC, sheremet-va approved these changes

2023-02-24 19:23 UTC, merged