fix: reload changed configuration file on watch mode
vitest-dev/vitest pull request #2889
Opened 2023-02-20 09:31 UTC by AriPerkkio

- Fixes issues where configuration file changes were not reloaded in watch mode, https://github.com/vitest-dev/vitest/pull/2886#issuecomment-1436519446

The `options` here is mutated by multiple Vite hooks.

https://github.com/vitest-dev/vitest/blob/b67a5fbdf9940191573c5f90d94be7a2ecb26a36/packages/vitest/src/node/plugins/index.ts#L155-L161

Once it has been initialized by first server setup, the `deepMerge` will take previous values of `options` instead of using the fresh `viteConfig`. This PR will restore the `options` back to initial values when in watch mode.

Tested watch mode locally in linked project by changing `test.reporters` and `test.coverage.provider`. I don't think Vitest has any watch mode related tests set so just manual testing for now.

2023-02-20 09:41 UTC, sheremet-va requested changes
Also I don't really understand what is happening here, can you add a comment about why a reset is needed?

2023-02-20 09:41 UTC, sheremet-va commented on packages/vitest/src/node/plugins/index.ts
> +        if (options.watch) {
Why `options.watch`? watch mode can be configured in the config

2023-02-20 10:05 UTC, AriPerkkio commented
> Also I don't really understand what is happening here

The `VitestPlugin` is created only once. Its hooks are called first when server is initially set up, and again always when watch mode re-triggers it. As the hooks are modifying the given `options`, the `deepMerge` on the shown lines will behave differently when watch mode re-triggers. 

https://github.com/vitest-dev/vitest/blob/b67a5fbdf9940191573c5f90d94be7a2ecb26a36/packages/vitest/src/node/plugins/index.ts#L155-L161

Here on the first run the `options` is the `CliOptions`. On second run it is the complete merged configuration of the first run, as `VitestPlugin` is not re-created. As `options` is the last argument, it has priority over the `viteConfigTest`. So the fresh values from `viteConfigTest` are overwritten by earlier run's `options`. 

To be honest it's quite difficult to follow the flow here as all hooks are sharing the mutable `options` and modifying it. Does the explanation make any sense? 😅

2023-02-25 07:54 UTC, sheremet-va commented
Conflict 👀

2023-02-25 08:05 UTC, sheremet-va approved these changes

2023-02-25 08:06 UTC, merged