docs(migration): Mention non-obvious renaming
vitest-dev/vitest pull request #2927
Opened 2023-02-27 16:40 UTC by carlobeltrame

Me and a colleague of mine were confused at first when we didn't find a vi.requireActual method, even when searching the documentation. This should hopefully clear things up for other people migrating from jest.

2023-02-27 16:55 UTC, sheremet-va requested changes

2023-02-27 16:55 UTC, sheremet-va commented on docs/guide/migration.md
> ++ const { cloneDeep } = vi.importActual('lodash/cloneDeep')
`vi.importActual` is asynchronous, so this code will actually fail.

```suggestion
+ const { cloneDeep } = await vi.importActual('lodash/cloneDeep')
```

2023-02-27 16:55 UTC, sheremet-va commented on docs/guide/migration.md
> +If you are only partially mocking a package, you might have previously used Jest's function `requireActual`. In vitest, you should replace these calls by calls to the `vi.importActual` function.
```suggestion
If you are only partially mocking a package, you might have previously used Jest's function `requireActual`. In Vitest, you should replace these calls with `vi.importActual`.
```

2023-02-28 08:22 UTC, carlobeltrame commented on docs/guide/migration.md
> +If you are only partially mocking a package, you might have previously used Jest's function `requireActual`. In vitest, you should replace these calls by calls to the `vi.importActual` function.
Thank you, I adjusted the wording.

2023-02-28 15:11 UTC, sheremet-va approved these changes

2023-02-28 15:11 UTC, merged