feat: add `concurrent` option to `sequence` config
vitest-dev/vitest pull request #3604
Opened 2023-06-17 14:40 UTC by fenghan34

Close #3573

2023-06-19 07:44 UTC, sheremet-va requested changes

2023-06-19 07:44 UTC, sheremet-va commented on docs/config/index.md
> +
```suggestion
- **Version**: Since Vitest 0.32.2

```

2023-06-19 07:44 UTC, sheremet-va approved these changes

2023-06-19 08:20 UTC, merged

2023-11-20 10:23 UTC, aghArdeshir commented
Doesn't this Merge Request resolve https://github.com/vitest-dev/vitest/issues/3922?