fix: omit node built-in pollyfills in browser
vitest-dev/vitest pull request #3648
Opened 2023-06-23 07:24 UTC by Marcel-G

resolves: https://github.com/vitest-dev/vitest/issues/3299

The browser runner indiscriminately applies pollyfills for node builtin modules. AFAIK the only required pollyfill is `util` for the web UI to work properly.

2023-06-27 17:53 UTC, sheremet-va commented
We can also remove polyfills now with modern-node-polyfills package

2023-06-28 12:55 UTC, userquin commented on packages/browser/src/node/index.ts
> -          return useId
also needed

2023-06-28 13:13 UTC, Marcel-G commented
The name of this plugin now doesn't seem appropriate, any naming ideas?

https://github.com/vitest-dev/vitest/blob/064f56d448bec374ea44042934c5eddaf2150b2a/packages/browser/src/node/index.ts#L34

2023-06-28 13:15 UTC, userquin commented on packages/browser/src/node/index.ts
> +        if (!builtinModules.includes(id) && !id.startsWith('node:')) {
can you remove this redundant if statement?

2023-06-28 14:17 UTC, userquin commented on packages/browser/src/node/index.ts
> +        if (!builtinModules.includes(id) && !id.startsWith('node:')) {
it seems we need if statement back, sorry...

2023-06-29 07:30 UTC, Marcel-G commented
As far as I can tell `util` is still included by `@sinonjs/fake-timers`:

https://github.com/vitest-dev/vitest/blob/c8c1b4a6a32177934adda0d5705a1f7112c2d76b/packages/vitest/src/integrations/mock/timers.ts#L38

2023-06-29 07:34 UTC, sheremet-va commented
> As far as I can tell `util` is still included by `@sinonjs/fake-timers`:
> 
> https://github.com/vitest-dev/vitest/blob/c8c1b4a6a32177934adda0d5705a1f7112c2d76b/packages/vitest/src/integrations/mock/timers.ts#L38

1. It is included dynamically if running inside Node.js
2. We bundle it

2023-06-29 07:45 UTC, Marcel-G commented
Heres the error in the browser if we don't include `util` polyfill

```
__vite-browser-external:util:3 Uncaught (in promise) Error: Module "util" has been externalized for browser compatibility. Cannot access "util.default" in client code.  See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
    at Object.get (__vite-browser-external:util:3:11)
    at withGlobal (vendor-vi.f4f5ef45.js:1370:47)
    at vendor-vi.f4f5ef45.js:3017:32
    at vendor-vi.f4f5ef45.js:3023:3
```

2023-06-29 07:47 UTC, Marcel-G commented
Heres the error in the browser if we don't include `util` pollyfil

```
__vite-browser-external:util:3 Uncaught (in promise) Error: Module "util" has been externalized for browser compatibility. Cannot access "util.default" in client code.  See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
    at Object.get (__vite-browser-external:util:3:11)
    at withGlobal (vendor-vi.f4f5ef45.js:1370:47)
    at vendor-vi.f4f5ef45.js:3017:32
    at vendor-vi.f4f5ef45.js:3023:3
```

2023-06-29 07:49 UTC, sheremet-va commented
> Heres the error in the browser if we don't include `util` pollyfil
> 
> ```
> __vite-browser-external:util:3 Uncaught (in promise) Error: Module "util" has been externalized for browser compatibility. Cannot access "util.default" in client code.  See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
>     at Object.get (__vite-browser-external:util:3:11)
>     at withGlobal (vendor-vi.f4f5ef45.js:1370:47)
>     at vendor-vi.f4f5ef45.js:3017:32
>     at vendor-vi.f4f5ef45.js:3023:3
> ```

Probably because we have `process` mocked, which we also shouldn't do, but it should be addressed in a separate issue.

2023-06-29 09:33 UTC, Marcel-G commented
> Probably because we have `process` mocked, which we also shouldn't do, but it should be addressed in a separate issue.

Something like this https://github.com/vitest-dev/vitest/pull/3701?

2023-06-29 09:33 UTC, sheremet-va commented
> > Probably because we have `process` mocked, which we also shouldn't do, but it should be addressed in a separate issue.
> 
> Something like this #3701?

Yes

2023-06-29 09:34 UTC, sheremet-va commented
> Heres the error in the browser if we don't include `util` pollyfil

Why are tests passing then 🤔

2023-06-29 09:37 UTC, Marcel-G commented
> > Heres the error in the browser if we don't include `util` pollyfil
> 
> Why are tests passing then 🤔

Sorry, In the current state `modern-node-polyfills` is still applied to `util` but I'll fix it up

2023-06-29 11:39 UTC, Marcel-G commented
OK, the tests will fail until https://github.com/vitest-dev/vitest/pull/3701 is in

2023-06-29 14:45 UTC, sheremet-va requested changes
`normalizeId` is not used anymore

2023-07-07 08:49 UTC, Marcel-G commented
> `normalizeId` is not used anymore

Very true! Removed ✅

2023-07-13 07:21 UTC, Marcel-G commented
@sheremet-va are the tests generally a bit flakey? It seems to be a different spec failing each time

2023-07-13 07:23 UTC, sheremet-va commented
> @sheremet-va are the tests generally a bit flakey? It seems to be a different spec failing each time

Some tests are flaky. Your PR is open until we have a browser test in ecosystem-ci

2023-09-04 14:15 UTC, Marcel-G commented
> Some tests are flaky. Your PR is open until we have a browser test in ecosystem-ci

@sheremet-va what is the status of that? is it something I can help with?

2023-09-22 13:53 UTC, sheremet-va commented
> > Some tests are flaky. Your PR is open until we have a browser test in ecosystem-ci
> 
> @sheremet-va what is the status of that? is it something I can help with?

Sorry for keeping you waiting! I am working on a small test suite for ecosystem-ci now, we can probably merge this PR today or next week.

2023-09-27 17:34 UTC, merged

2023-10-03 16:41 UTC, AriPerkkio commented
How should the `util` be polyfilled now? It's still used by `@sinon-js/fake-timers`. v1-beta fails with error `SyntaxError: The requested module '/node_modules/.pnpm/util@0.12.5/node_modules/util/util.js?v=c8f99d41' does not provide an export named '__vi_inject__'`. And when adding `"vitest > util"` to `optimizeDeps.include`, it fails with:

```
ReferenceError: process is not defined
 ❯ node_modules/.pnpm/util@0.12.5/node_modules/util/util.js ../../../../node_modules/.vite/deps/vitest___util.js:1308:5
 ❯ __require ../../../../node_modules/.vite/deps/chunk-UXIASGQL.js:9:50
 ❯ ../../../../node_modules/.vite/deps/vitest___util.js:1799:25
 ```

2023-10-03 16:45 UTC, sheremet-va commented
> How should the `util` be polyfilled now?

Vitest doesn't use it and as far as I know `@sinonjs/fake-timers` checks it at runtime, so this _shouldn't_ be a problem? If it is, maybe we can patch it and inline the package?

> And when adding `"vitest > util"` to `optimizeDeps.include`, it fails with:

The error looks correct to me since we don't define a global `process` variable since it doesn't exist in the browser.

2023-10-03 17:07 UTC, AriPerkkio commented
> Vitest doesn't use it 

Looks like `@vitest/browser` imports `vitest/runners`, which uses `vi`. Importing `vi` brings in inlined fake-timers which has `process`.

2023-10-03 17:11 UTC, sheremet-va commented
> > Vitest doesn't use it
> 
> Looks like `@vitest/browser` imports `vitest/runners`, which uses `vi`. Importing `vi` brings in inlined fake-timers which has `process`. The `vendor-vi` has `import require$$2 from 'util';`.

fake-timers have a check for `process`. What I assume happened in your case is that polyfill is using `process` for some reason.

> The `vendor-vi` has `import require$$2 from 'util';`.

Yeah, this is why I am saying we should just patch fake timers to remove this check.