feat: global setup
vitest-dev/vitest pull request #372
Opened 2021-12-30 13:10 UTC by dominikg

fixes #300 

ideas for tests, documentation and api improvements welcome

2021-12-30 14:09 UTC, patak-dev commented
Great! About the API, is there a reason we want to use a file-based API instead of accepting the setup function in the config?

```
/// <reference types="vitest" />

import { defineConfig } from 'vite'

export default defineConfig({
  test: {
    global: true,
    globalSetup: async function() {
      const server = await startServer()
      return async() => {
        await server.close()
      }
    },
  }
})
```
Is the idea that it could be less verbose because you normally will need to import this function from a file anyways? Maybe we could accept a function (or array of functions), but still, allow to pass a file name as a shortcut? (with the same API as you propose, but it looks better as an optional shortcut than as the API for this feature to me... but maybe everyone is very used to using files for this purpose)

2021-12-30 14:45 UTC, dominikg commented
i did take a cue from jests feature which uses files (likely because their config can also be json) and it aligns with vitest's own `setupFiles` 

Directly using a function in config would simplify the internal implementation which i like a lot. But then you'd have to use regular imports for all the things you want/need in setup and that could bloat the config itself. I'm leaning towards the file approach due to prior art and dx result.

But if using the function approach enables ts support without extra work and the bloat is not an issue i'm all for it. in the end jest users can write a simple wrapper around their existing files and import that

2021-12-30 16:11 UTC, patak-dev commented
What about providing both ways? (both in `setupFiles` and `globalSetup`). You can pass a setup function (with optional cleanup as a return param) or a module path if that is more comfortable (or a list of these). I know this will be two ways to do the same things, but seeing the module path as a shortcut for the real function seems a good way to justify it (and also due to compat). We could maybe avoid the named exports in the module version and only accept the default export form to simplify the API?
@antfu do you have a preference here?

2021-12-30 16:43 UTC, antfu commented
The `setupFiles` can't be an inline function as it is supposed to be running in each worker with different environments. For `globalSetup` I see no problem with that.

2021-12-30 19:50 UTC, dominikg commented
implementation as function here: https://github.com/dominikg/vitest/tree/feat/global-setup-function

the complexity in vitest is greatly reduced, except for this "hack": https://github.com/dominikg/vitest/blob/22c5ec2ef05c4001ffaff43d581914c2328e2e62/packages/vitest/src/node/pool.ts#L80

passing a function does not work.

Unfortunately stacktraces don't look great when globalSetup gets bundled into the config:

```shell
20:26 $ pnpm test

> @vitest/test-globalSetup@ test /home/dominikg/develop/vitest/test/global-setup
> vitest

file:///home/dominikg/develop/vitest/test/global-setup/vitest.config.ts.js?t=1640892430013:9
  throw new Error("ooops");
        ^

Error: ooops
    at vitest_global_setup_default (file:///home/dominikg/develop/vitest/test/global-setup/vitest.config.ts.js?t=1640892430013:9:9)
```

2022-01-04 07:03 UTC, mitchelvanbever requested changes

2022-01-04 07:03 UTC, mitchelvanbever commented on docs/config/index.md
> +Multiple globalSetup files are possible. setup and teardown are executed sequentially with teardown in reverse order.
Maybe adding a callout to this will do it a little more justice 🙂

2022-01-04 07:03 UTC, mitchelvanbever commented on docs/config/index.md
> +Files can either export named functions
```suggestion
Example 
```

2022-01-04 07:03 UTC, mitchelvanbever commented on docs/config/index.md
> +```js
Could be all in one example (divised by comments to show the different approaches

2022-01-04 11:30 UTC, mitchelvanbever approved these changes

2022-01-10 08:48 UTC, antfu commented
Let's ship it for now, and we can see how we could improve the stacktrace later.

2022-01-10 08:48 UTC, antfu approved these changes

2022-01-10 09:15 UTC, dominikg commented
The stacktraces in this PR should be fine. I'm still a bit worried about the intermittent test failures. Havn't been able to reliably reproduce/debug it unfortunately as it only happens on windows and trying to get to the bottom of a possible v8 issue inside a virtual machine running windows hasn't been a great experience at all.

maybe @userquin has an idea? 

Steps to try to reproduce:
* checkout this PR
* run `pnpm i && pnpm build` 
* run `pnpm test:ci` 

sometimes it fails with an error like this (different testcases)

```shell
examples/vue test: FATAL ERROR: v8::FromJust Maybe value is Nothing.
examples/vue test:  1: 00007FF63D8E30AF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112511
examples/vue test:  2: 00007FF63D872216 DSA_meth_get_flags+65542
examples/vue test:  3: 00007FF63D8730CD node::OnFatalError+301
examples/vue test:  4: 00007FF63E18F4C5 v8::V8::FromJustIsNothing+53
examples/vue test:  5: 00007FF63D85B203 v8::base::CPU::has_sse+31491
examples/vue test:  6: 00007FF63D945BF7 uv_timer_stop+1207
examples/vue test:  7: 00007FF63D9421CB uv_async_send+331
examples/vue test:  8: 00007FF63D94195C uv_loop_init+1292
examples/vue test:  9: 00007FF63D941AFA uv_run+202
examples/vue test: 10: 00007FF63D910C05 node::SpinEventLoop+309
examples/vue test: 11: 00007FF63D7AB4D0 v8::internal::wasm::SignatureMap::Freeze+35776
examples/vue test: 12: 00007FF63D7A6B28 v8::internal::wasm::SignatureMap::Freeze+16920
examples/vue test: 13: 00007FF63D9322DD uv_poll_stop+557
examples/vue test: 14: 00007FF63E743DF0 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146416
examples/vue test: 15: 00007FFC64087034 BaseThreadInitThunk+20
examples/vue test: 16: 00007FFC64E82651 RtlUserThreadStart+33
examples/vue test: Failed
undefined
```

2022-01-10 10:14 UTC, merged

2022-01-13 16:10 UTC, bhvngt commented
I was trying out this feature and came across this peculiar issue. I am using an isomorphic library [supabase-js](https://github.com/supabase/supabase-js). When I import it in a file that is sourced by `globalSetup`, it throws following error.

```
21:38:19 [vite] Error when evaluating SSR module /node_modules/@supabase/supabase-js/dist/main/index.js:
ReferenceError: exports is not defined
    at eval (/node_modules/@supabase/supabase-js/dist/main/index.js:17:23)
    at instantiateModule (/home/projects/node-3cxxqh/node_modules/vite/dist/node/chunks/dep-76613303.js:60094:15)
21:38:19 [vite] Error when evaluating SSR module ./test/globalSetup.ts:
ReferenceError: exports is not defined
    at eval (/node_modules/@supabase/supabase-js/dist/main/index.js:17:23)
    at instantiateModule (/home/projects/node-3cxxqh/node_modules/vite/dist/node/chunks/dep-76613303.js:60094:15)
(node:6) UnhandledPromiseRejectionWarning: ReferenceError: exports is not defined
    at eval (/node_modules/@supabase/supabase-js/dist/main/index.js:17:23)
    at instantiateModule (/home/projects/node-3cxxqh/node_modules/vite/dist/node/chunks/dep-76613303.js:60094:15)
```

When I import the same in a normal test file it works fine.

Here's the [playground](https://stackblitz.com/edit/node-3cxxqh) where the error is reproduced.

2022-01-13 16:21 UTC, patak-dev commented
@bhvngt could you create an issue with this info so it is easier to track it?

2022-01-13 16:40 UTC, bhvngt commented
@patak-dev #522