docs: improve globs
vitest-dev/vitest pull request #3737
Opened 2023-07-04 10:43 UTC by nickmccurdy

Documents #3392

2023-07-04 10:59 UTC, sheremet-va approved these changes

2023-07-05 07:51 UTC, dammy001 commented on docs/config/index.md
> +Files to include in the test run, using glob patterns. By default it looks for files in any folders named `__tests__` with the extensions `.js`,`.mjs`, `.cjs`, `.ts`, `.mts`, `.cts`, `.jsx`, and `.js
```suggestion
Files to include in the test run, using glob patterns. By default it looks for files in any folders named `__tests__` with the extensions `.js`,`.mjs`, `.cjs`, `.ts`, `.mts`, `.cts`, `.jsx`, and `.tsx`. It also includes files ending with `.test` or `.spec` along with files just named `test` or `spec` (before a valid extension). These patterns are compatible with Vitest default patterns but with additional extensions.
```

2023-07-05 08:16 UTC, dammy001 commented on docs/config/index.md
> +Files to include in typechecking test runs, using glob patterns. By default all tests inside files ending with `test-d` along with files just named `test-d` are considered type tests.
```suggestion
Files to include in typechecking test runs, using glob patterns. By default, all tests inside files ending with `test-d` along with files just named `test-d` are considered type tests. 
```

2023-07-05 08:36 UTC, antfu requested changes
I don't think we should move forward on this. As mentioned in https://github.com/vitest-dev/vitest/issues/3530#issuecomment-1620440424, I think we should revert this behavior and consider it as a regression. And if we are going to do it, I rather not document it as it will confuse users when are we will going to change it back soon.

2023-07-08 11:30 UTC, antfu commented
Close this as we reverted this behaviour in the recent minor: https://github.com/vitest-dev/vitest/pull/3729

Thanks for bringing this up

2023-07-08 11:30 UTC, closed without merging