feat: support `describe.sequential`
vitest-dev/vitest pull request #3771
Opened 2023-07-14 10:34 UTC by fenghan34

Closes #3731

2023-07-14 11:27 UTC, sheremet-va requested changes
Documentation is missing

2023-07-15 16:55 UTC, dammy001 commented on docs/api/index.md
> +  `describe.sequential` in a suite marks every tests as sequential. This is useful if you want to run tests in sequential within `describe.concurrent` or with the `--sequence.concurrent` command opti
```suggestion
  `describe.sequential` in a suite marks every test as sequential. This is useful if you want to run tests in sequential within `describe.concurrent` or with the `--sequence.concurrent` command option.
```

2023-07-16 02:10 UTC, fenghan34 commented on docs/api/index.md
> +  `describe.sequential` in a suite marks every tests as sequential. This is useful if you want to run tests in sequential within `describe.concurrent` or with the `--sequence.concurrent` command opti
Thank you for reviewing!

2023-07-16 12:34 UTC, dammy001 approved these changes

2023-07-19 15:14 UTC, merged