fix(core): test change should trigger failed test rerun
vitest-dev/vitest pull request #3773
Opened 2023-07-15 02:54 UTC by btea

fix #3687

2023-07-15 07:49 UTC, AriPerkkio requested changes
- Add test case to `test/watch/test/stdin.test.ts`
- The implementation doesn't seem to consider the filter enabled by pressing `f`? This PR should only affect that use case.

2023-07-15 08:01 UTC, btea commented
> * The implementation doesn't seem to consider the filter enabled by pressing `f`? This PR should only affect that use case.

Maybe I misunderstood you guys? I thought that as long as the test content is modified, if there is a failed test case, it will automatically rerun.

2023-07-19 19:16 UTC, AriPerkkio requested changes
> Maybe I misunderstood you guys? I thought that as long as the test content is modified, if there is a failed test case, it will automatically rerun.
> 
> I seem to understand that only after pressing `f`, if the content of the test file is modified, the failed test will be automatically run, is it?

The issue contains two bugs:

- When user has activated "Run only failed test"-filter in watch mode by pressing `f`, this filter does not preserve if files are modified
- The "Run only failed test"-filter runs all **test cases** inside **test files**. It should run only failed **test cases**. Now it's only filtering the files.

2023-07-19 19:16 UTC, AriPerkkio commented on test/watch/test/stdin.test.ts
> +test('rerun failed tests', async () => {
We'll need a test case that fails in `main`, and is fixed by these changes. This test case does not fail on `main` branch. 

Maybe something like below?

```ts
test('rerun failed tests', async () => {
  const testPath = 'fixtures/error.test.ts'
  const failAssertion = 'expect(1).toBe(2)'
  const testCase = `// Dynamic test case
  import { test, expect } from 'vitest'

  // Failure re-run should run this
  test('failing test', () => {
    ${failAssertion}
  })

  // Failure re-run should NOT run this
  test('passing test', () => {
    expect(1).toBe(1)
  })
  `

  writeFileSync(testPath, testCase, 'utf8')
  cleanups.push(() => rmSync(testPath))

  const vitest = await runVitestCli(...cliArgs)
  await vitest.waitForStdout('Test Files  1 failed | 2 passed (3)')
  await vitest.waitForStdout('Tests  1 failed | 3 passed (4)')

  // Re-run failed tests only
  vitest.write('f')

  // Only a single test should have run
  await vitest.waitForStdout('Test Files  1 failed (1)')

  // Only a single test case should have run
  await vitest.waitForStdout('Tests  1 failed (1)')

  // Fix failing test case
  writeFileSync(testPath, testCase.replace(failAssertion, ''), 'utf8')

  // Only the previously failed test file should run
  await vitest.waitForStdout('Test Files  1 pass (1)')

  // Only the previously failed test case should run
  await vitest.waitForStdout('Tests  1 pass (1)')
})
```

2023-07-19 19:16 UTC, AriPerkkio commented on packages/vitest/src/node/stdin.ts
> +      ctx.isFailedModel = false
I don't think we should set properties of `ctx` outside it like this. Could this filter be toggled on/off inside the `core.ts` instead?

But your approach is right in the way that we indeed need to save the failure filter in state.

2023-07-21 03:56 UTC, btea commented
> The issue contains two bugs:
> 
> * When user has activated "Run only failed test"-filter in watch mode by pressing `f`, this filter does not preserve if files are modified
> * The "Run only failed test"-filter runs all **test cases** inside **test files**. It should run only failed **test cases**. Now it's only filtering the files.

If I didn't understand the error, it means that if a test file has test cases that fail, after pressing `f`, only the failed suite in the test file is re-run instead of the entire test file and all cases are re-run? (If so, filter test cases in a test file, I don't know how to do it, can you give me a hint? Thanks.)

And if the content of the file is modified, the failed test will not be filtered, and the original operation logic can be followed.

2023-07-24 06:17 UTC, AriPerkkio commented
> (If so, filter test cases in a test file, I don't know how to do it, can you give me a hint? Thanks.)

I'm not 100% sure, but the changes should be made somewhere around `packages/runner` I think.

2023-07-30 12:46 UTC, btea commented
Sorry, I can't seem to find any relevant instructions in the official documentation. Maybe I'm missing something. 🤔

@sheremet-va  Can you give me a little hint? Thanks!

2024-07-01 16:18 UTC, sheremet-va commented
> @sheremet-va Can you give me a little hint? Thanks!

I'm not sure, but I think you can set `configOverride.testNamePattern` to filter tests (this is what vscode does) - maybe we should improve this somehow internally 🤷🏻

2026-03-19 12:34 UTC, sheremet-va commented
Seems like this was fixed at one point

2026-03-19 12:34 UTC, closed without merging