feat: support config junit reporter className with env
vitest-dev/vitest pull request #3808
Opened 2023-07-25 07:49 UTC by InfiniteXyy

Add some partial config for https://github.com/vitest-dev/vitest/issues/3691

It would be helpful if some want don't want the `filePath` to be in the `className `in Junit reporter

2023-07-25 10:35 UTC, AriPerkkio requested changes
I guess this change is fine for now. As long term solution we should allow configuring reporter specific options: https://github.com/vitest-dev/vitest/issues/3691#issuecomment-1611162791

2023-07-25 10:35 UTC, AriPerkkio commented on packages/vitest/src/node/reporters/junit.ts
> +        classname: process.env.VITEST_JUNIT_CLASSNAME ?? filename,
Update documentation too:

https://github.com/vitest-dev/vitest/blob/b7ce1959bd469b83c3b7035579b7583386503489/docs/config/index.md?plain=1#L486

2023-07-26 03:13 UTC, InfiniteXyy commented on packages/vitest/src/node/reporters/junit.ts
> +        classname: process.env.VITEST_JUNIT_CLASSNAME ?? filename,
Added
```md
JUnit XML reporter (you can configure `testsuites` tag name with `VITEST_JUNIT_SUITE_NAME` environmental variable, and `classname` tag property with `VITEST_JUNIT_CLASSNAME`)
```

2023-07-26 05:39 UTC, AriPerkkio approved these changes

2023-07-28 10:03 UTC, sheremet-va approved these changes

2023-07-28 10:03 UTC, merged