doc: add writing tests section in getting started
vitest-dev/vitest pull request #3843
Opened 2023-07-29 17:33 UTC by Jannchie

This PR resolved #3800.

I went through the official Jest documentation to add a brief introduction to writing tests to the Getting Started section.

2023-07-29 17:44 UTC, sheremet-va requested changes

2023-07-29 17:44 UTC, sheremet-va commented on docs/guide/index.md
> +Finally, run `yarn test`, `npm test` or `pnpm test` and Vitest will print this message:
```suggestion
Finally, run `npm run test`, `yarn test`, or `pnpm test`, depending on your package manager, and Vitest will print this message:
```

2023-07-29 19:36 UTC, sheremet-va commented
Lint is failing

2023-07-30 05:13 UTC, Jannchie commented
> Lint is failing

Fixed..!

2023-07-30 08:47 UTC, merged