fix: indicator position of error message
vitest-dev/vitest pull request #3855
Opened 2023-08-01 10:36 UTC by fenghan34

Fixes #3766

2023-08-01 10:54 UTC, sheremet-va requested changes
Please, add a test. And don't remove the PR description

2023-08-01 10:55 UTC, fenghan34 commented
It seems that I can't push CRLF formatted files. How can I add tests for this, Do you have any suggestions? @sheremet-va

2023-08-01 10:56 UTC, sheremet-va commented
> It seems that I can't push CRLF formatted files. How can I add tests for this, Do you have any suggestions? @sheremet-va

I don't know what you mean by "I can't push CRLF formatted files". Is it an eslint rule? You can disable it in a single file.

2023-08-01 10:57 UTC, sheremet-va commented
You can also just test a single function call.

2023-08-01 11:25 UTC, fenghan34 commented
>  I don't know what you mean by "I can't push CRLF formatted files"

It's not eslint rule. This issue relates to CRLF format, see https://github.com/vitest-dev/vitest/issues/3766#issuecomment-1637145601. 

To add a test, I need to create a CRLF format test file, but we have the `.gitattributes` config, and it tells git to normalize all line endings to LF.

2023-08-01 11:27 UTC, fenghan34 commented
> You can also just test a single function call.

What do you mean by "test a single function call"?

2023-08-01 11:29 UTC, fenghan34 commented
Can I add a line to `.gitattributes`? Seems like we can specify a single file in CRLF format

2023-08-01 11:32 UTC, sheremet-va commented
> Can I add a line to `.gitattributes`? Seems like we can specify a single file in CRLF format

Sure

2023-08-01 16:07 UTC, sheremet-va approved these changes

2023-08-02 07:45 UTC, sheremet-va requested changes

2023-08-02 07:45 UTC, sheremet-va commented on test/reporters/fixtures/indicator-position.test.ts
> +/* eslint-disable no-multiple-empty-lines */
I think this file should be javascript because esbuild truncates all empty lines.

2023-08-02 11:12 UTC, sheremet-va approved these changes

2023-08-02 11:12 UTC, sheremet-va commented
LGTM 👍

2023-08-03 07:45 UTC, merged

2023-08-15 16:51 UTC, mcavigelli commented
Thanks a lot for the fix!