fix(runner): `test.extend` doesn't work in hooks without test
vitest-dev/vitest pull request #4065
Opened 2023-09-03 14:50 UTC by Dunqing

### Description

fix: #4030 

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

2023-09-05 13:39 UTC, sheremet-va requested changes

2023-09-05 16:10 UTC, Dunqing commented on test/core/test/hooks-top-level.test.ts
> +const test = originalTest.extend<Fixture>({
> What happens in `beforeEah` if you call `extend` with the context that provides the same names? (Which is a viable option)
> 
> ```ts
> const test1 = test.extend({ foo: 1 })
> const test2 = test.extend({ foo: 2 })
> ```
> 

You can see the test cases, The context of `test1` and `test2` are unrelated.


> I think providing hooks on a test is a better alternative:
> 
> ```ts
> const test1 = test.extend({ foo: 1 })
> test1.beforeEach(({ foo }) => {
>   foo === 1
> })
> test1('contexted', ({ foo }) => {
>   expect(foo).toBe(1)
> })
> ```

In `vitest`, the `test1.beforeEach` doesn't support yet, the API supported in `playwright`

2023-09-08 08:18 UTC, sheremet-va commented on test/core/test/hooks-top-level.test.ts
> +const test = originalTest.extend<Fixture>({
Ok then. API looks good to me, but tests are failing.

2023-09-08 08:51 UTC, Dunqing commented
I think the test failure has nothing to do with this PR

2023-09-08 09:03 UTC, sheremet-va commented
> I think the test failure has nothing to do with this PR

Only Windows and Mac tests are flaky, the Ubuntu one I see for the first time.

2023-09-08 12:16 UTC, Dunqing commented
I figured out why, since concurrent causes an error caused by the fact that the test fetched by `getCurrentTest()` may not be correct. Now I get `fixtures` from context because the context is right in concurrent

2023-09-14 08:22 UTC, merged