fix(browser): support more browsers
vitest-dev/vitest pull request #4320
Opened 2023-10-17 07:22 UTC by edoardocavazza

### Description

This PR solves #4304 adding the `es2017` target to builds and polyfilling `globalThis` in html entrypoints.

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

2023-10-17 07:24 UTC, sheremet-va commented
We should not polyfill anything by default.

2023-10-17 07:35 UTC, edoardocavazza commented
I see. I've removed the polyfill for globalThis, which will narrow down the list of supported browsers a bit, particularly excluding Safari versions up to 12.2, but I think it should still work.

2023-11-16 10:11 UTC, sheremet-va requested changes
Should we also add spy package here?

2024-10-02 15:16 UTC, closed without merging

2024-10-02 15:16 UTC, sheremet-va commented
#4304 is closed