fix: fix crash when using happy-dom or jsdom environment on Yarn PnP workspaces
vitest-dev/vitest pull request #4698
Opened 2023-12-07 21:24 UTC by wojtekmaj

close #4413

### Description

Fixes an issue with Vitest crashing with cryptic error:

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
{ type: 'Unhandled Error', stacks: [] }

```

when using happy-dom or jsdom environment on Yarn PnP workspaces (note: this is NOT happening in "just" Yarn PnP).

Similarly to #4657, this "lifts" the logic up from local-pkg in order for PnP not to complain about local-pkg accessing packages that are not declared as its dependencies or peerDependencies.

I was unsure what to do `pnpm-lock.yaml` because this PR technically adds a direct dependency (in reality, it "lifts" it, since it's already used in `local-pkg`), so lockfile had to be modified...

How I tested it:

1. Ran unit tests in my workspace using vitest + happy-dom, expecting failures, after removing [workaround mentioned in #4413](https://github.com/vitest-dev/vitest/issues/4413#issuecomment-1790347687):

```
wmaj@MacBook-Air-2 react-ui % yarn unit

 RUN  v1.0.2 /packages/packages/react-ui

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 9 unhandled errors during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
{ type: 'Unhandled Error', stacks: [] }

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
{ type: 'Unhandled Error', stacks: [] }

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
{ type: 'Unhandled Error', stacks: [] }

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
{ type: 'Unhandled Error', stacks: [] }

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
{ type: 'Unhandled Error', stacks: [] }

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
{ type: 'Unhandled Error', stacks: [] }

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
{ type: 'Unhandled Error', stacks: [] }

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
{ type: 'Unhandled Error', stacks: [] }

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
{ type: 'Unhandled Error', stacks: [] }
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files  no tests
      Tests  no tests
     Errors  9 errors
   Start at  22:13:08
   Duration  775ms (transform 3ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 0ms)
```

2. Built vitest from source; copied `dist` directory to `.yarn/unplugged/vitest-virtual-64d4633324/node_modules/vitest/dist`; reinstalled repo:

```
wmaj@MacBook-Air-2 react-ui % yarn     
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 206ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 0s 408ms
```

3. Re-ran tests:

```
wmaj@MacBook-Air-2 react-ui % yarn unit

 RUN  v1.0.2 /packages/packages/react-ui

 ✓ textarea_field/index.spec.tsx (1)
 ✓ button_link/index.spec.tsx (1)
 ✓ radio_field/index.spec.tsx (6)
 ✓ input_field/index.spec.tsx (5)
 ✓ toggle/index.spec.tsx (7)
 ✓ checkbox_field/index.spec.tsx (8)
 ✓ select_field/index.spec.tsx (2)
 ✓ link_button/index.spec.tsx (1)
 ✓ button/index.spec.tsx (1)

 Test Files  9 passed (9)
      Tests  32 passed (32)
   Start at  22:16:27
   Duration  3.69s (transform 470ms, setup 2.74s, collect 2.79s, tests 503ms, environment 6.15s, prepare 2.86s)
```

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

2023-12-07 23:04 UTC, sheremet-va requested changes

2023-12-07 23:04 UTC, sheremet-va commented on packages/vitest/package.json
> +    "mlly": "^1.4.2",
mlly was intentionally removed from dependencies during beta. let's not being the whole acorn parser just for a simple function

2023-12-08 10:53 UTC, wojtekmaj commented on packages/vitest/package.json
> +    "mlly": "^1.4.2",
But we DO have mlly already. It's local-pkg's dependency anyway.

2023-12-08 11:10 UTC, sheremet-va commented on packages/vitest/package.json
> +    "mlly": "^1.4.2",
Removing local-pkg is the next step

2023-12-08 13:44 UTC, wojtekmaj commented on packages/vitest/package.json
> +    "mlly": "^1.4.2",
A PoC fix presented in #4413 worked for me, but without interopDefault from mlly, we're essentially just import()ing, and this wrapper is of no use.

This seems like a right thing to do, but we did just that before, and in #1712 we reverted to importModule (containing interopDefault) because of #1709.

What would you suggest?

2023-12-08 14:31 UTC, sheremet-va commented on packages/vitest/package.json
> +    "mlly": "^1.4.2",
1. I think we might be able to just do something like this:

```ts
const pkgName = 'jsdom'
const win = await import(pkgName) as import('jsdom')
```

2. We don't run this file through a Vite transform pipeline anymore so just doing `import('jsdom')` should already work.

2023-12-09 20:34 UTC, wojtekmaj commented on packages/vitest/package.json
> +    "mlly": "^1.4.2",
Thanks for your input! Changed my code to as desired.

2023-12-09 20:35 UTC, wojtekmaj commented on packages/vitest/package.json
> +    "mlly": "^1.4.2",
Fun fact: this leaves is with only two instances of local-pkg usage; should be relatively easy!

2023-12-11 15:43 UTC, sheremet-va commented on packages/vitest/package.json
> +    "mlly": "^1.4.2",
I remembered another use case for this - if Vitest is running globally, then this will fail unless jsdom is installed globally, which would be a regression.

We can maybe call `rpc.resolveId('jsdom')` to get the file path

2023-12-13 10:30 UTC, wojtekmaj commented on packages/vitest/package.json
> +    "mlly": "^1.4.2",
Would you be kind enough to pick it up from here? I think this goes beyond what I understand. :D

2023-12-28 12:30 UTC, sheremet-va commented on packages/vitest/package.json
> +    "mlly": "^1.4.2",
After having another look, the solution is actually a working one

2023-12-28 12:32 UTC, sheremet-va approved these changes

2023-12-28 12:43 UTC, merged