fix(vitest): test deep dependencies change detection
vitest-dev/vitest pull request #4934
Opened 2024-01-11 12:29 UTC by blake-newman

`--changed` flag is not correctly looking up deep dependencies, as such the changed flag does not trigger specs if a sub dependency is changed.

Alters the logic to add the collected dependency after recursive `addImports` is called, otherwise the logic returns early because that dependency has already been added to the collected deps set. So it will not look deeply.

Resolves #4933

2024-01-18 10:08 UTC, hi-ogawa reviewed
Thanks for the PR! (also reproduction and your analysis are awesome!)

This looks like a bug to me since the same logic is also used for `vitest related` https://vitest.dev/guide/cli.html#vitest-related and it also misses deep dependency. I checked it based on your repro https://stackblitz.com/edit/github-ndav2w?file=package.json

For the sake of verifying this PR, I don't think setting up new tests for `--changed` is necessary (actually there seems none currently probably because it's tedious to setup git), but It would be great if you can expand existing tests in `test/changed/fixtures/related` to show that deep dependencies is covered.

2024-01-18 10:08 UTC, hi-ogawa commented on packages/vitest/src/node/core.ts
> +        deps.add(filepath)
nit: this is probably just a minor thing, but I think we could just accumulating everything but filter `workspaceFilepath` later? something like:

```tsx
  const addImports = async (...) => {
      if (deps.has(filepath))
        return
      deps.add(filepath)
      ...
  } 

  await addImports(filepath)
  deps.delete(filepath[1])
```

2024-01-19 10:00 UTC, sheremet-va requested changes
Let's add a test case for this change. The tests for this feature are located in `test/changed`

2024-01-19 10:50 UTC, blake-newman commented
@sheremet-va @hi-ogawa i've added the relevant tests (including imports / re-export syntax). 

I also tested locally to ensure that the specs fail if the changes are not applied.

2024-01-19 15:54 UTC, sheremet-va approved these changes

2024-01-20 01:48 UTC, hi-ogawa approved these changes
Looks good!

2024-01-20 07:39 UTC, merged