fix(test): update RTL test example
vitest-dev/vitest pull request #523
Opened 2022-01-13 19:14 UTC by horacioh

update the React Testing Library tests

2022-01-13 21:32 UTC, antfu requested changes

2022-01-13 21:32 UTC, antfu commented on package.json
> +    "test": "^0.6.0"
what's is this for?

2022-01-13 21:32 UTC, antfu commented on packages/ui/client/components/DetailsPanel.vue
> -    <div p="y1" text-sm items-center gap-2 :class="color" w-full flex select-none cursor-pointer>
Can you revert these format changes?

2022-01-13 22:43 UTC, horacioh commented on package.json
> +    "test": "^0.6.0"
uops! my bad!

2022-01-13 22:43 UTC, horacioh commented on packages/ui/client/components/DetailsPanel.vue
> -    <div p="y1" text-sm items-center gap-2 :class="color" w-full flex select-none cursor-pointer>
done!

2022-01-14 01:12 UTC, antfu commented
Please keep unrelated files unchanged, thanks

2022-01-14 07:10 UTC, horacioh commented
hey @antfu !

do you prefer I redo the PR just by changing the example code? let me know what do you think is best!

thanks!

2022-01-14 08:17 UTC, antfu commented
I don't mind how you do it, but it seems

- Your formatter is formating files under `/ui`
- You used `yarn` which we are using `pnpm`

2022-01-14 08:22 UTC, dammy001 commented
Yeah... @antfu i think you should add preinstall hook to allow only pnpm 🤔

2022-01-14 11:51 UTC, mitchelvanbever requested changes
Thanks for checking it out. Left some comments and I do think there is bigger problem at play here.

Whenever you include @testing-library/jest-dom the types for all vitest related stuff gets overwritten by @types/jest

2022-01-14 11:51 UTC, mitchelvanbever commented on examples/react-testing-lib/src/App.test.tsx
> +    await render(<App />)
No need to await the render

2022-01-14 11:51 UTC, mitchelvanbever commented on examples/react-testing-lib/src/App.test.tsx
> +    const btn = await screen.findByRole('button')
also no need to await this

2022-01-14 11:51 UTC, mitchelvanbever commented on examples/react-testing-lib/src/App.test.tsx
> +    await waitFor(() => {
Now here you probably want to await but preferably without waitFor

2022-01-14 11:51 UTC, mitchelvanbever commented on examples/react-testing-lib/src/App.test.tsx
> +import '@testing-library/jest-dom'
Probably best to use a setupFile

2022-01-14 12:01 UTC, sheremet-va commented
> Whenever you include @testing-library/jest-dom the types for all vitest related stuff gets overwritten by @types/jest

We have an open issue for this https://github.com/vitest-dev/vitest/issues/517

2022-01-14 12:59 UTC, horacioh commented
thanks everyone that review this PR!. I decided to create a new cleaner on with all the suggestions and fixes. you can check it out here #530 . Going to close this one!

Cheers!

2022-01-14 12:59 UTC, closed without merging