fix: add async to onFinish report event
vitest-dev/vitest pull request #623
Opened 2022-01-24 19:24 UTC by edimitchel

![image](https://user-images.githubusercontent.com/2922851/150850224-11cbe73f-d866-4d08-9477-9d2be6ebc6c4.png)

2022-01-24 19:41 UTC, Demivan commented
Adding `async` to a function that does not have `await` should not affect it. What does this do?

2022-01-24 19:49 UTC, edimitchel commented
async behind a function transform the function to a awaitable.

The function report which make sure to send report event needs function which return promise.
See https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/node/core.ts#L378-L381

2022-01-24 19:59 UTC, Demivan commented
Ok, makes sense that this will return a promise now.
Should this be extended to `onCollected` and `onUserConsoleLog`? Those are marked as awaitable in reporter interface too.

2022-01-24 20:05 UTC, prazdevs commented
Hi, tested it on my repo that was crashing on `--ui` it works perfectly fine now and reruns as expected ! 👍

2022-01-24 20:09 UTC, mitchelvanbever commented
> Hi, tested it on my repo that was crashing on `--ui` it works perfectly fine now and reruns as expected ! 👍

Same here 👌

2022-01-24 20:17 UTC, edimitchel commented
> Ok, makes sense that this will return a promise now.
> Should this be extended to onCollected and onUserConsoleLog? Those are marked as awaitable in reporter interface too.

Good comment, I think we can remove the Awaitable type.

2022-01-25 07:29 UTC, sheremet-va requested changes
I think it's better to make them all `Awaitable` to support async implementation in reporters. Also shouldn't they await `Promise.all` and not just turn into an async function?

2022-01-25 09:08 UTC, antfu commented
Actually, events prefixed with `on` should not expect returns (error on receiver side does not matter to the sender), add it here https://github.com/vitest-dev/vitest/blob/c23be109deb67f796bc31edb61d3acbb306fea49/packages/vitest/src/api/setup.ts#L104
Should work

2022-01-25 10:05 UTC, bjarkihall commented
Thanks for the PR!
For those trying to find an issue/PR a text would work better than a screenshot when searching, so I'll just paste it here:
```
(node:50984) UnhandledPromiseRejectionWarning: Error: listen EACCES: permission denied 127.0.0.1:51204
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:50984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:50984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, 
promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

2022-01-25 12:17 UTC, antfu commented
I have made the fix in 6b02dea and released it as v0.2.3. Please check if it fixes the error

2022-01-25 13:14 UTC, bjarkihall commented
@antfu I've tried `v.0.2.3` on a clean install (using npm) but still get the same error message when running `npx vitest --ui`
`npx vitest` itself still works without any problems.
This is likely the same issue as the one reported in https://github.com/vitest-dev/vitest/issues/627

2022-01-25 16:22 UTC, mitchelvanbever commented
> I have made the fix in [6b02dea](https://github.com/vitest-dev/vitest/commit/6b02deaa9b68fdd89c86bf010f56f5e60cbbae27) and released it as v0.2.3. Please check if it fixes the error

I've now tested two local repo's that had the issue prior to V0.2.3 but after upgrading I'm no longer seeing the messages and/or crashes happening (with and without ui flag).

Stackblitz seems to not complain anymore as well.

2022-01-25 17:02 UTC, bjarkihall commented
@mitchelvanbever on a second look at the original image from @edimitchel, the error messages are indeed not the same, although they both show a similar warning + stacktrace (both caused by unhandled promise rejections).

This one is related to custom reporters.
I'll follow up on this in the issue I linked to `--ui` (#627).

Any ideas how unhandled promise rejections could be further prevented or at least caught, for the sake of a clearer stacktrace?

2022-01-27 09:06 UTC, edimitchel commented
@antfu what should we do ?

2022-02-04 06:33 UTC, sheremet-va commented
> @antfu what should we do ?

I think it should be fixed now. Can you confirm? If so, we may close the PR

2022-02-09 22:47 UTC, closed without merging