fix(browser): fix viewport for non ui case
vitest-dev/vitest pull request #6512
Opened 2024-09-15 09:32 UTC by hi-ogawa

### Description

- closes https://github.com/vitest-dev/vitest/issues/6485

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

2024-09-15 10:53 UTC, sheremet-va requested changes
This doesn't fix it when you call `page.viewport`

We already experimented with this before. Now we just need to keep the same iframe scaling that we have in ui

2024-09-16 01:11 UTC, hi-ogawa commented
> This doesn't fix it when you call `page.viewport`

Ah, I didn't think about that. I've read https://github.com/vitest-dev/vitest/pull/6257 and scaling seems more involved but I'll see what I can do.

2024-09-18 05:28 UTC, hi-ogawa reviewed
Only Mac chromium playwright is timing out with `specs/runner.test.ts` https://github.com/vitest-dev/vitest/actions/runs/10915841527/job/30296283296?pr=6512#step:9:24

I cannot reproduce it locally on my Linux chromium headless, so it's hard to diagnose what's wrong. I would appreciate if someone can check it on Mac machine locally.

2024-09-18 05:28 UTC, hi-ogawa commented on test/browser/test/userEvent.test.ts
> +      y: expect.closeTo(150, -1),
Scaling round issue seems to already exist for UI case. I can reproduce it on main branch with firefox.

```ts
$ PROVIDER=playwright BROWSER=firefox pnpm -C test/browser test-fixtures /userEvent. -t 'x/y'

 FAIL  test/userEvent.test.ts > userEvent.click > clicks with x/y coords
AssertionError: expected "spy" to be called with arguments: [ { x: 200, y: 150 } ]

Received: 

  1st spy call:

  Array [
    Object {
-     "x": 200,
+     "x": 199,
      "y": 150,
    },
  ]
```

2024-09-18 05:28 UTC, hi-ogawa commented on packages/browser/src/client/orchestrator.ts
> +  else if (getBrowserState().provider === 'playwright') {
I couldn't figure out what's wrong with webdriverio, so I added scaling only for `playwright` and CI seems mostly happy.

2024-10-14 01:17 UTC, hi-ogawa commented
@sheremet-va I did some CI debugging, but couldn't figure out mac chromium fail. The CI log suggests `test/browser/test/...` hangs somewhere and it might be reproduced locally with headless or non ui. Can you try this on your PC?

```sh
# or --browser.ui=false
pnpm -C test/browser test-fixtures --browser.headless=true
```

2025-01-21 18:28 UTC, nstepien commented
Is this still blocked?

2025-02-15 05:32 UTC, hi-ogawa commented
I updated a branch but Mac seems still flaky. The last run passed but 2nd last run seemed stuck in timeout.

2025-04-03 05:00 UTC, hi-ogawa commented
Hopefully flakiness is finally gone...

2025-04-03 12:47 UTC, sheremet-va requested changes

2025-04-03 12:47 UTC, sheremet-va commented on packages/browser/src/client/tester/utils.ts
> +  if (scaleAttribute === null) {
We should always add a `data-scale` attribute and throw an error if it's incorrect. The `isNaN` check after that checks exactly that scenario

2025-04-16 15:27 UTC, sheremet-va approved these changes

2025-04-17 10:57 UTC, merged