docs: added more description about connecting UI with right mode.
vitest-dev/vitest pull request #7119
Opened 2024-12-23 05:23 UTC by bandhan-majumder

Added more description for connecting UI with right mode to avoid confusion.

### Description

While reading the [guide](https://vitest.dev/guide/ui) about Vitest UI, most of us try to run it with `vitest run` and the UI never connects. It is made for `watch` mode. I have added a `warning` about this usage and also mentioned the area where information about `HTML` reported is given for `run` mode.

### Fixes
It's an old issue. I am not creating a new issue for the same. Instead, referencing the previous one which asks for a documentation update to avoid confusion.

Details: #2897

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [ ] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [ ] Ideally, include a test that fails without this PR but passes with it.
- [ ] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [ ] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [ ] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

2024-12-29 18:28 UTC, bandhan-majumder commented
Hi @sheremet-va . Can you please review it as it may help others to avoid confusion with just few lines added.

2025-01-13 16:19 UTC, sheremet-va requested changes

2025-01-13 16:19 UTC, sheremet-va commented on docs/guide/ui.md
> +Make sure you are running it in `watch` mode as it's **not supported** for `run` mode. HTML reporter can be used instead to get generated HTML page with the same results. More details are provided in
```suggestion
The UI is interactive and requires a running Vite server, so make sure to run Vitest in `watch` mode (the default). Alternatively, you can generate a static HTML report that looks identical to the Vitest UI by specifying `html` in config's `reporters` option.
```

2025-01-13 16:19 UTC, sheremet-va approved these changes

2025-01-13 16:19 UTC, merged