fix (core): filter different projects in watch mode
vitest-dev/vitest pull request #7146
Opened 2024-12-29 08:10 UTC by DevJoaoLopes

### Description

closes #7131 

- This PR resolves a bug in watch (-watch) mode where the filter (w key) is not filtering only the tests of a given project

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [ ] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

2025-01-03 12:13 UTC, sheremet-va requested changes

2025-01-03 12:13 UTC, sheremet-va commented on packages/vitest/src/node/core.ts
>      const specifications = files.flatMap(file => this.getModuleSpecifications(file))
This should already return only filtered projects because it uses `vitest.projects` and not `vitest.resolvedProjects`. Why doesn't it?

2025-01-03 12:13 UTC, sheremet-va commented on test/filterWatchMode/package.json
> +{
Can you move the test to `test/watch`?

2025-01-03 22:17 UTC, DevJoaoLopes commented on packages/vitest/src/node/core.ts
>      const specifications = files.flatMap(file => this.getModuleSpecifications(file))
Yes, but in those cases where we have different projects defined by `defineProject`, the filter of `files.flatMap(file => this.getModuleSpecifications(file))` is returning TestProjects beyond what it should.
Because of this, one of the possible solutions would be to apply the filter by name.

2025-01-03 23:28 UTC, sheremet-va commented on packages/vitest/src/node/core.ts
>      const specifications = files.flatMap(file => this.getModuleSpecifications(file))
You just rephrased what I asked. Why does it do that? `getModuleSpecification` shouldn't include filtered out projects

2025-01-08 23:26 UTC, DevJoaoLopes commented on test/filterWatchMode/package.json
> +{
moved for `test/watch` @sheremet-va

2025-01-08 23:26 UTC, DevJoaoLopes commented on packages/vitest/src/node/core.ts
>      const specifications = files.flatMap(file => this.getModuleSpecifications(file))
@sheremet-va Do you have any idea what paths we can take to solve the problem? Insert validation into `specificationsWithFilterByProject` or remove cache validation for `getModuleSpecification` ?

2025-01-13 13:52 UTC, sheremet-va commented on packages/vitest/src/node/core.ts
>      const specifications = files.flatMap(file => this.getModuleSpecifications(file))
We can invalidate all cache if projects array is changed

2025-01-15 23:48 UTC, DevJoaoLopes commented on packages/vitest/src/node/core.ts
>      const specifications = files.flatMap(file => this.getModuleSpecifications(file))
@sheremet-va  done, if you can review please

2025-01-19 20:07 UTC, DevJoaoLopes reviewed
Removed cache so we have the projects filtered properly.

2025-01-19 20:15 UTC, sheremet-va commented
> Removed cache so we have the projects filtered properly.

I said "invalidate" the cache, not remove the if check

2025-01-19 20:40 UTC, DevJoaoLopes commented
> > Removed cache so we have the projects filtered properly.
> 
> I said "invalidate" the cache, not remove the if check

okay, then I'll have to think about how to do that

2025-01-19 23:48 UTC, DevJoaoLopes commented
> > > Removed cache so we have the projects filtered properly.
> > 
> > 
> > I said "invalidate" the cache, not remove the if check
> 
> okay, then I'll have to think about how to do that

@sheremet-va One of the ways to maintain this cache validation was to enter a condition to compare filtered projects by invalidating the cache when there are differences.

2025-01-23 13:01 UTC, closed without merging