fix: only use locator.element on last expect.element attempt (fix #7139)
vitest-dev/vitest pull request #7152
Opened 2024-12-31 19:36 UTC by tsirlucas

### Description

Fixes memory leak caused by multiple prettyDOM calls during expect.element retries.

ref: https://github.com/vitest-dev/vitest/issues/7139

### Please don't delete this checklist! Before submitting the PR, please make sure you do the following:
- [x] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
- [x] Ideally, include a test that fails without this PR but passes with it.
- [x] Please, don't make changes to `pnpm-lock.yaml` unless you introduce a new test example.

### Tests
- [x] Run the tests with `pnpm test:ci`.

### Documentation
- [x] If you introduce new functionality, document it. You can run documentation with `pnpm run docs` command.

### Changesets
- [x] Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.

2024-12-31 20:34 UTC, tsirlucas commented on test/browser/specs/runner.test.ts
> +    expect(browserResultJson.testResults).toHaveLength(20 * instances.length)
is this correct? i assumed i needed to bump those since i added new test cases

2025-01-03 12:23 UTC, sheremet-va requested changes

2025-01-03 12:23 UTC, sheremet-va commented on packages/browser/src/client/tester/expect-element.ts
> +      const isLastPollAttempt = chai.util.flag(this, '_isLastPollAttempt')
let's also add a comment why we are doing this with a link to an issue

2025-01-03 12:23 UTC, sheremet-va commented on packages/vitest/src/integrations/chai/poll.ts
> +              await check()
this check can succeed or throw an error, this needs special handling

2025-01-03 12:23 UTC, sheremet-va commented on packages/vitest/src/integrations/chai/poll.ts
> +            timeoutId = setTimeout(async () => {
let's not make it async

2025-01-03 12:23 UTC, sheremet-va commented on test/browser/test/expect-element.test.ts
> +  locator.element = locatorElementMock
you can just do `vi.spyOn()`

2025-01-03 13:33 UTC, tsirlucas commented on packages/vitest/src/integrations/chai/poll.ts
> +              await check()
hey

from what i can see the `check` function declaration is already using a try/catch block and handling the error.

if the assertion succeeds, it will resolve the promise successfuly
if the assertion fails, it will end in the catch block and wont throw an error

so the only scenario check can throw an error is if `chai.util.flag` access for some reason throw. if you want me to handle that case, can you provide more details on how? you want specific behavior or just logging?

im adding test cases for both scenarios: sucess/failure on last attempt

i added two new test cases to cover such scenarios

2025-01-03 13:34 UTC, tsirlucas commented on packages/vitest/src/integrations/chai/poll.ts
> +            timeoutId = setTimeout(async () => {
i need to be able to await the `check` call. do you want me to use `Promise.then` instead?
can do it NP, just want to make sure we are aligned

2025-01-03 13:54 UTC, sheremet-va commented on packages/vitest/src/integrations/chai/poll.ts
> +            timeoutId = setTimeout(async () => {
Yes, I meant using `promise.then.catch`

2025-01-03 13:55 UTC, sheremet-va commented on packages/vitest/src/integrations/chai/poll.ts
> +              await check()
I see, I guess the name is a bit misleading. We don't need an error handling here then

2025-01-03 15:08 UTC, sheremet-va commented
LGMT! Thank you!

2025-01-03 15:08 UTC, merged