fix: support for define global constants
vitest-dev/vitest pull request #743
Opened 2022-02-12 17:05 UTC by poyoho

fix: #706

use vite load module and exec the module in the vm, the pr support the define var in the vm.

2022-02-12 18:03 UTC, sheremet-va requested changes
Did you find the real reason why contant's weren't defined in Vue?

2022-02-12 18:03 UTC, sheremet-va commented on packages/vitest/src/node/execute.ts
> +      ...process.__vitest_worker__.config.define,
this will kill coverage :p /cc @Demivan

2022-02-12 18:19 UTC, sheremet-va commented
Also shouldn't they be statically replaced? And not just declared on a global?

2022-02-13 05:14 UTC, poyoho commented
> Did you find the real reason why contant's weren't defined in Vue?

the file will generate vite ssr code, and exec in the vm. and the vm don't had load vite env. vite env inject the global vari when run in the serve or ssr mode.

2022-02-13 07:09 UTC, antfu commented
Oh, interesting finding. But I guess importing `/@vite/env` once should be enough.
You can try to have `await runner.executeId('/@vite/env')` before:
https://github.com/vitest-dev/vitest/blob/d55736dbf5b9f708065a2b8d2bf787679db7e232/packages/vite-node/src/cli.ts#L87-L88

2022-02-13 07:40 UTC, poyoho commented
oh, they only run in the difference worker, vm had the same context with worker 😂

2022-02-13 08:03 UTC, sheremet-va approved these changes

2022-02-13 08:44 UTC, Demivan approved these changes

2022-02-13 10:16 UTC, merged