feat: add typeof assertion
vitest-dev/vitest pull request #762
Opened 2022-02-15 19:49 UTC by Shinigami92

This adds a new assertion that replaces `expect(typeof actual).toBe('string')` with `expect(actual).toBeTypeOf('string')`

2022-02-15 19:57 UTC, sheremet-va requested changes
You would need to add docs to `api/index.md` i think
And test should be _somewere_ in the `test/core/test` 👀

2022-02-15 19:57 UTC, sheremet-va commented on packages/vitest/src/integrations/chai/jest-expect.ts
> +    const expected = obj
Maybe restructure a little bit? :p

```ts
function (expected) {
   const actual = typeof this._obj
   const equal = expected === actual
   // ...
}
```

2022-02-15 20:00 UTC, sheremet-va commented
> Somehow there is a chai typeOf https://www.chaijs.com/api/assert/#method_typeof
I think it is accesible with:

```ts
import { assert } from 'chai'
assert.typeOf()
```

2022-02-15 20:11 UTC, Shinigami92 commented
> I think it is accesible with:
> 
> ```ts
> import { assert } from 'chai'
> assert.typeOf()
> ```

Tested this, but it's not so accurate and the negation with `.not.toBeTypeOf` shows the wrong message.
So I will leave it as I implemented it :slightly_smiling_face:

2022-02-15 20:27 UTC, Shinigami92 commented
@sheremet-va Ready for a second review :rocket: 
Thanks for your review

2022-02-15 20:32 UTC, sheremet-va approved these changes
LGTM
Thank you for PR!

2022-02-15 21:12 UTC, patak-dev commented
Nice! About the name, shouldn't it be `toHaveType` instead of `toBeTypeOf`
```
expect(actual).toBeOfType('string')
```
because it is
```
typeof actual === 'string'
```
So, the **type of actual** is string
And we want to say now that we expect actual to be **of type string**

It is different than for `toBeInstanceOf`, as with it the construct is `actual instanceof expected`. So the API for it in Jest sounds right.

2022-02-15 21:23 UTC, Shinigami92 commented
> Nice! About the name, shouldn't it be `toBeOfType` instead of `toBeTypeOf`
> 
> ```
> expect(actual).toBeOfType('string')
> ```
> 
> because it is
> 
> ```
> typeof actual === 'string'
> ```
> 
> So, the **type of actual** is string And we want to say now that we expect actual to be **of type string**
> 
> It is different than for `toBeInstanceOf`, as with it the construct is `actual instanceof expected`. So the API for it in Jest sounds right.

Yes and no, cause there is the real `typeof actual === 'string'`, it's named after this `typeof` where folks are familiar with

2022-02-15 21:32 UTC, patak-dev commented
I think that every other API in expect reads well. IMO, even if some users may initially reach out `toBeTypeOf('string')`, the correct naming here is `toBeOfType('string')` and with TS and autocomplete people shouldn't have issues finding/using it. @sheremet-va ?

2022-02-15 21:42 UTC, Shinigami92 commented
> I think that every other API in expect reads well. IMO, even if some users may initially reach out `toBeTypeOf('string')`, the correct naming here is `toBeOfType('string')` and with TS and autocomplete people shouldn't have issues finding/using it. @sheremet-va ?

Would you be at least satisfied with an alias?
I also already thought about aliases like `typeOf` and `notTypeOf` and such.
Like currently you can use e.g. `expect(...).toMatch()` or `expect(...).match()`

2022-02-15 21:47 UTC, patak-dev commented
For reference, regarding the naming in chai, there it is 
```
assert.typeOf('tea', 'string', 'we have a string');
```
but that reads well: **type of 'tea'** is 'string'

2022-02-15 22:05 UTC, ST-DDT approved these changes

2022-02-16 04:04 UTC, sheremet-va commented
> I think that every other API in expect reads well. IMO, even if some users may initially reach out `toBeTypeOf('string')`, the correct naming here is `toBeOfType('string')` and with TS and autocomplete people shouldn't have issues finding/using it. @sheremet-va ?
> 
> 
> 
> 

I like the current version because it is consistent with toBeInctanceOf

2022-02-16 04:51 UTC, patak-dev commented
> I like the current version because it is consistent with toBeInctanceOf

But it isnt consistent to me 🤔
It is different than for toBeInstanceOf, as with it the construct is actual instanceof expected. So the API for it in Jest sounds right.
```
typeof actual === expected
actual instanceof expected
```
the `of` refers to actual in the first, and to expected in the second

Grammarly complains for "Expect something to be type of string". And the casing, TypeOf instead of typeof also affects here.

2022-02-16 05:25 UTC, Aslemammad commented
`toBeTypeOf` is more accessible, but `toBeOfType` suits well here, and I guess it can be easily found with TS! so no problem on that side, and even if some users have trouble with that naming, we can mention it in the docs why we prefer `toBeOfType`!

2022-02-16 05:43 UTC, antfu approved these changes

2022-02-16 05:45 UTC, antfu commented
I'd vote for `toBeTypeOf` as it matches the wording order of the keyword `typeof`, which to me will be more intuitive and easier to find.

2022-02-16 06:08 UTC, merged