fix: fixed toMatch not to maintain the regex state which has global flag
vitest-dev/vitest pull request #777
Opened 2022-02-17 15:05 UTC by togami2864

Using chai's `match`, `regex.lastIndex` is maintained even if global flag is raised. 

<img width="377" alt="スクリーンショット 2022-02-17 23 39 59" src="https://user-images.githubusercontent.com/62130798/154508353-81a10c0e-af29-409d-a776-9475ba2744c3.png">

This PR changed the truth check from chai's `match` to `RegExp` constructor.

2022-02-17 16:17 UTC, sheremet-va requested changes

2022-02-17 16:17 UTC, sheremet-va commented on packages/vitest/src/integrations/chai/jest-expect.ts
> +      return new RegExp(expected).test(received)
returning doesn't actually do anything 👀 
you need to use `this.assert`
also a comment would be nice to have explaining the decision

2022-02-19 11:52 UTC, antfu commented
I am not so sure if we should do that implictly. I would feel that user should be responsible to reset the regex as this is how JS regex works.

2022-02-20 08:30 UTC, togami2864 commented
That's true. I misunderstood the spec of the global flag.
This might be a bad change, since it forces the `lastIndex` to be reset by rebuilding the instance and exec it implicitly:thinking:

2022-02-21 05:21 UTC, closed without merging